-- Tests for buffer.lua. Run: luajit test/buffer_test.lua (from repo root)
package.path = "vendor/lust/?.lua;./?.lua;" .. package.path

local lust   = require("lust")
local buffer = require("buffer")
local describe, it, expect = lust.describe, lust.it, lust.expect

describe("buffer", function()
  describe("new / parsing", function()
    it("splits lines and detects a final newline (eol)", function()
      local b = buffer.new("a\nb\nc\n")
      expect(b:nlines()).to.equal(3)
      expect(b:get()).to.equal({ "a", "b", "c" })
      expect(b.noeol).to.be(false)
    end)

    it("detects a missing final newline (noeol)", function()
      local b = buffer.new("a\nb\nc")
      expect(b:nlines()).to.equal(3)
      expect(b.noeol).to.be(true)
    end)

    it("treats the empty string as the empty file", function()
      local b = buffer.new("")
      expect(b:nlines()).to.equal(1)
      expect(b:line(1)).to.equal("")
      expect(b.noeol).to.be(true)
    end)

    it("preserves interior blank lines", function()
      local b = buffer.new("a\n\nb\n")
      expect(b:get()).to.equal({ "a", "", "b" })
    end)

    it("handles a lone newline as one empty line with eol", function()
      local b = buffer.new("\n")
      expect(b:get()).to.equal({ "" })
      expect(b.noeol).to.be(false)
    end)

    it("round-trips text() for both eol and noeol", function()
      for _, s in ipairs({ "a\nb\nc\n", "a\nb\nc", "", "\n", "x" }) do
        expect(buffer.new(s):text()).to.equal(s)
      end
    end)
  end)

  describe("queries", function()
    it("returns nil for out-of-range line()", function()
      local b = buffer.new("a\nb")
      expect(b:line(0)).to_not.exist()
      expect(b:line(3)).to_not.exist()
    end)

    it("get() returns an independent copy", function()
      local b = buffer.new("a\nb\nc")
      local g = b:get(1, 2)
      g[1] = "MUT"
      expect(b:line(1)).to.equal("a")
    end)

    it("get() rejects a bad range", function()
      local b = buffer.new("a\nb")
      expect(function() b:get(1, 9) end).to.fail()
    end)
  end)

  describe("set", function()
    it("replaces a line and marks modified", function()
      local b = buffer.new("a\nb\nc")
      expect(b.modified).to.be(false)
      b:set(2, "B")
      expect(b:get()).to.equal({ "a", "B", "c" })
      expect(b.modified).to.be(true)
    end)

    it("rejects a newline in a line", function()
      local b = buffer.new("a")
      expect(function() b:set(1, "x\ny") end).to.fail()
    end)

    it("rejects an out-of-range line", function()
      local b = buffer.new("a")
      expect(function() b:set(2, "x") end).to.fail()
    end)
  end)

  describe("insert", function()
    it("inserts before a line", function()
      local b = buffer.new("a\nb\nc")
      b:insert(2, { "X", "Y" })
      expect(b:get()).to.equal({ "a", "X", "Y", "b", "c" })
    end)

    it("prepends at line 1", function()
      local b = buffer.new("a\nb")
      b:insert(1, { "P" })
      expect(b:get()).to.equal({ "P", "a", "b" })
    end)

    it("appends at nlines()+1", function()
      local b = buffer.new("a\nb")
      b:insert(3, { "Z" })
      expect(b:get()).to.equal({ "a", "b", "Z" })
    end)

    it("rejects out-of-range and newline-bearing inserts", function()
      local b = buffer.new("a")
      expect(function() b:insert(5, { "x" }) end).to.fail()
      expect(function() b:insert(1, { "x\ny" }) end).to.fail()
    end)
  end)

  describe("delete", function()
    it("removes an interior range", function()
      local b = buffer.new("a\nb\nc\nd")
      b:delete(2, 3)
      expect(b:get()).to.equal({ "a", "d" })
    end)

    it("keeps one empty line when emptied", function()
      local b = buffer.new("a\nb\nc")
      b:delete(1, 3)
      expect(b:nlines()).to.equal(1)
      expect(b:line(1)).to.equal("")
    end)

    it("rejects a bad range", function()
      local b = buffer.new("a\nb")
      expect(function() b:delete(1, 5) end).to.fail()
    end)
  end)

  describe("open / write round-trip", function()
    it("writes and reads back byte-for-byte, honoring noeol", function()
      for _, s in ipairs({ "a\nb\nc\n", "a\nb\nc", "" }) do
        local tmp = os.tmpname()
        local b = buffer.new(s)
        b:write(tmp)
        local b2 = buffer.open(tmp)
        expect(b2:text()).to.equal(s)
        expect(b2.noeol).to.be(b.noeol)
        expect(b2.modified).to.be(false)
        os.remove(tmp)
      end
    end)

    it("opens a missing file as an empty buffer bound to the path", function()
      local p = os.tmpname(); os.remove(p) -- ensure it does not exist
      local b = buffer.open(p)
      expect(b:nlines()).to.equal(1)
      expect(b.path).to.equal(p)
    end)
  end)

  describe("undo / redo", function()
    it("undoes a set, insert, and delete", function()
      local b = buffer.new("a\nb\nc")
      b:set(2, "X"); b:undo(); expect(b:get()).to.equal({ "a", "b", "c" })
      b:insert(2, { "N" }); b:undo(); expect(b:get()).to.equal({ "a", "b", "c" })
      b:delete(2, 2); b:undo(); expect(b:get()).to.equal({ "a", "b", "c" })
    end)
    it("undoes a whole-buffer delete (the guard case)", function()
      local b = buffer.new("a\nb\nc")
      b:delete(1, 3)
      expect(b:get()).to.equal({ "" })
      b:undo()
      expect(b:get()).to.equal({ "a", "b", "c" })
    end)
    it("redoes an undone change", function()
      local b = buffer.new("x")
      b:set(1, "y"); b:undo(); expect(b:line(1)).to.equal("x")
      b:redo(); expect(b:line(1)).to.equal("y")
    end)
    it("groups changes by checkpoint (multi-level)", function()
      local b = buffer.new("a")
      b:set(1, "b"); b:undo_checkpoint()
      b:set(1, "c")
      b:undo(); expect(b:line(1)).to.equal("b")
      b:undo(); expect(b:line(1)).to.equal("a")
    end)
    it("a fresh edit invalidates the redo stack", function()
      local b = buffer.new("a")
      b:set(1, "b"); b:undo()          -- back to "a", "b" is redoable
      b:set(1, "c")                    -- new edit clears redo
      expect(b:redo()).to_not.exist()
      expect(b:line(1)).to.equal("c")
    end)
    it("returns nil with nothing to undo", function()
      expect(buffer.new("a"):undo()).to_not.exist()
    end)
  end)
end)

os.exit(lust.errors == 0 and 0 or 1) -- non-zero exit on any failure (for CI)
