-- Tests for ex.lua (the shared dispatcher). Run: luajit test/ex_test.lua
package.path = "vendor/lust/?.lua;./?.lua;" .. package.path

local lust   = require("lust")
local buffer = require("buffer")
local ex     = require("ex")
local describe, it, expect = lust.describe, lust.it, lust.expect

local function ed_with(text)
  return { buf = buffer.new(text), cx = 1, cy = 1, top = 1, running = true,
           rows = 24, cols = 80, mode = "normal" }
end

describe("ex.dispatch", function()
  describe("addresses", function()
    it("a bare address moves the cursor", function()
      local ed = ed_with("a\nb\nc\nd")
      local _, s = ex.dispatch(ed, "3")
      expect(s).to.equal("ok")
      expect(ed.cy).to.equal(3)
    end)
    it("clamps an out-of-range address", function()
      local ed = ed_with("a\nb\nc")
      ex.dispatch(ed, "99")
      expect(ed.cy).to.equal(3)
    end)
  end)

  describe("print", function()
    it("prints a range", function()
      local ed = ed_with("a\nb\nc\nd")
      local p, s = ex.dispatch(ed, "2,3p")
      expect(s).to.equal("ok")
      expect(p).to.equal("b\nc")
    end)
    it("% prints the whole buffer", function()
      local ed = ed_with("a\nb\nc")
      expect((ex.dispatch(ed, "%p"))).to.equal("a\nb\nc")
    end)
    it("defaults to the current line", function()
      local ed = ed_with("a\nb\nc"); ed.cy = 2
      expect((ex.dispatch(ed, "p"))).to.equal("b")
    end)
  end)

  describe("delete", function()
    it("deletes a range and repositions the cursor", function()
      local ed = ed_with("a\nb\nc\nd")
      local _, s = ex.dispatch(ed, "2,3d")
      expect(s).to.equal("ok")
      expect(ed.buf:get()).to.equal({ "a", "d" })
      expect(ed.cy).to.equal(2)
    end)
    it("defaults to the current line", function()
      local ed = ed_with("a\nb\nc"); ed.cy = 1
      ex.dispatch(ed, "d")
      expect(ed.buf:get()).to.equal({ "b", "c" })
    end)
  end)

  describe("quit", function()
    it("refuses when modified, unless forced", function()
      local ed = ed_with("a\nb")
      ed.buf:set(1, "X")                       -- make it modified
      local _, s = ex.dispatch(ed, "q")
      expect(s).to.equal("err")
      expect(ed.running).to.be(true)
      local _, s2 = ex.dispatch(ed, "q!")
      expect(s2).to.equal("ok")
      expect(ed.running).to.be(false)
    end)
    it("quits a clean buffer", function()
      local ed = ed_with("a")
      local _, s = ex.dispatch(ed, "q")
      expect(s).to.equal("ok")
      expect(ed.running).to.be(false)
    end)
  end)

  describe("write", function()
    it("writes to a path and reports bytes", function()
      local ed = ed_with("a\nb\n")
      local tmp = os.tmpname()
      local p, s = ex.dispatch(ed, "w " .. tmp)
      expect(s).to.equal("ok")
      expect(p:find("written", 1, true)).to.exist()
      expect(ed.buf.modified).to.be(false)
      local f = io.open(tmp, "rb"); local body = f:read("*a"); f:close()
      expect(body).to.equal("a\nb\n")
      os.remove(tmp)
    end)
    it("errors without a file name", function()
      local ed = ed_with("a")
      local _, s = ex.dispatch(ed, "w")
      expect(s).to.equal("err")
    end)
  end)

  describe("set", function()
    it("toggles wrap and queries it", function()
      local ed = ed_with("x")
      ex.dispatch(ed, "set nowrap")
      expect((ex.dispatch(ed, "set wrap?"))).to.equal("nowrap")
      ex.dispatch(ed, "set wrap")
      expect((ex.dispatch(ed, "set wrap?"))).to.equal("wrap")
    end)
    it("toggles a boolean with a trailing !", function()
      local ed = ed_with("x")                    -- wrap defaults on
      ex.dispatch(ed, "set wrap!")
      expect((ex.dispatch(ed, "set wrap?"))).to.equal("nowrap")
      ex.dispatch(ed, "set wrap!")
      expect((ex.dispatch(ed, "set wrap?"))).to.equal("wrap")
    end)
    it("errors toggling a non-boolean", function()
      local _, s = ex.dispatch(ed_with("x"), "set tabstop!")
      expect(s).to.equal("err")
    end)
    it("sets a numeric option", function()
      local ed = ed_with("x")
      ex.dispatch(ed, "set tabstop=4")
      expect((ex.dispatch(ed, "set tabstop?"))).to.equal("tabstop=4")
    end)
    it("errors on an unknown option", function()
      local _, s = ex.dispatch(ed_with("x"), "set bogus")
      expect(s).to.equal("err")
    end)
  end)

  describe("highlights and position", function()
    it("sets and clears named highlight groups", function()
      local ed = ed_with("hello\nworld")
      ex.dispatch(ed, "hl search 1:1-3 2:1")
      expect(ed.highlights.search[1]).to.equal({ line = 1, c1 = 1, c2 = 3 })
      expect(ed.highlights.search[2]).to.equal({ line = 2, c1 = 1, c2 = 1 })
      ex.dispatch(ed, "nohl")
      expect(next(ed.highlights)).to_not.exist()
    end)
    it("rejects a bad highlight spec", function()
      local _, s = ex.dispatch(ed_with("x"), "hl g nonsense")
      expect(s).to.equal("err")
    end)
    it(":pos reports the cursor as line<TAB>col", function()
      local ed = ed_with("a\nb\nc")
      ex.dispatch(ed, "3")
      expect((ex.dispatch(ed, "pos"))).to.equal("3\t1")
    end)
  end)

  describe("shelling out", function()
    it(":!cmd captures output (no tty -> capture path)", function()
      local out, s = ex.dispatch(ed_with("x"), "!echo hello")
      expect(s).to.equal("ok")
      expect(out).to.equal("hello\n")
    end)
    it(":[range]!cmd filters lines through a command", function()
      local ed = ed_with("banana\napple\ncherry")
      local _, s = ex.dispatch(ed, "%!sort")
      expect(s).to.equal("ok")
      expect(ed.buf:get()).to.equal({ "apple", "banana", "cherry" })
    end)
    it("a filter is one undo", function()
      local ed = ed_with("b\na")
      ex.dispatch(ed, "%!sort")
      expect(ed.buf:get()).to.equal({ "a", "b" })
      ed.buf:undo()
      expect(ed.buf:get()).to.equal({ "b", "a" })
    end)
    it(":r !cmd reads command output into the buffer", function()
      local ed = ed_with("one\ntwo")
      ex.dispatch(ed, "r !printf 'A\\nB\\n'")
      expect(ed.buf:get()).to.equal({ "one", "A", "B", "two" })
    end)
    it(":r file reads a file", function()
      local p = os.tmpname(); local f = io.open(p, "wb"); f:write("X\nY\n"); f:close()
      local ed = ed_with("top")
      ex.dispatch(ed, "r " .. p)
      expect(ed.buf:get()).to.equal({ "top", "X", "Y" })
      os.remove(p)
    end)
    it(":silent runs the sub-command (capture path)", function()
      expect((ex.dispatch(ed_with("x"), "silent !echo hi"))).to.equal("hi\n")
    end)
    it("a failed filter preserves the buffer and reports the exit code", function()
      local ed = ed_with("keep\nthis\ntext")
      local _, s = ex.dispatch(ed, "%!false")           -- false exits 1
      expect(s).to.equal("err")
      expect(ed.buf:get()).to.equal({ "keep", "this", "text" })
    end)
    it(":!cmd reports a non-zero exit", function()
      local _, s = ex.dispatch(ed_with("x"), "!false")
      expect(s).to.equal("err")
    end)
    it("a failed :r !cmd inserts nothing", function()
      local ed = ed_with("a\nb")
      local _, s = ex.dispatch(ed, "r !false")
      expect(s).to.equal("err")
      expect(ed.buf:get()).to.equal({ "a", "b" })
    end)
  end)

  it("reports unknown commands", function()
    local ed = ed_with("a")
    local p, s = ex.dispatch(ed, "frobnicate")
    expect(s).to.equal("err")
    expect(p:find("unknown", 1, true)).to.exist()
  end)
end)

os.exit(lust.errors == 0 and 0 or 1)
