-- Tests for normal.lua (the coroutine interpreter). Run: luajit test/normal_test.lua
package.path = "vendor/lust/?.lua;./?.lua;" .. package.path

local lust   = require("lust")
local buffer = require("buffer")
local normal = require("normal")
local ex     = require("ex")
local describe, it, expect = lust.describe, lust.it, lust.expect

-- Build an editor state with a live interpreter coroutine, primed to getkey.
local function make(text)
  local ed = { buf = buffer.new(text), cx = 1, cy = 1, top = 1, rows = 24,
    cols = 80, mode = "normal", cmdline = "", message = nil,
    inject = {}, pending = {}, keylog = {}, regs = {}, marks = {}, running = true }
  ed.interp = coroutine.create(function() normal.loop(ed) end)
  assert(coroutine.resume(ed.interp))
  return ed
end

-- Feed a string of keys and let the coroutine drain them.
local function feed(ed, s)
  for i = 1, #s do ed.inject[#ed.inject + 1] = s:byte(i) end
  assert(coroutine.resume(ed.interp))
  return ed
end

local ESC = "\27"

describe("normal-mode interpreter", function()
  describe("motions", function()
    it("h j k l 0 $ move the cursor", function()
      local ed = make("abc\ndef")
      feed(ed, "ll"); expect(ed.cx).to.equal(3)
      feed(ed, "0");  expect(ed.cx).to.equal(1)
      feed(ed, "$");  expect(ed.cx).to.equal(3)
      feed(ed, "j");  expect(ed.cy).to.equal(2)
      feed(ed, "k");  expect(ed.cy).to.equal(1)
    end)
    it("honors a count", function()
      local ed = make("abcdef")
      feed(ed, "3l"); expect(ed.cx).to.equal(4)
    end)
    it("G goes to a line or the last line", function()
      local ed = make("a\nb\nc\nd")
      feed(ed, "G");  expect(ed.cy).to.equal(4)
      feed(ed, "2G"); expect(ed.cy).to.equal(2)
    end)
    it("w b e move by word within a line", function()
      local ed = make("foo bar baz")
      feed(ed, "w"); expect(ed.cx).to.equal(5)   -- start of 'bar'
      feed(ed, "e"); expect(ed.cx).to.equal(7)   -- end of 'bar'
      feed(ed, "b"); expect(ed.cx).to.equal(5)   -- back to start of 'bar'
    end)
  end)

  describe("find motions f t F T ; ,", function()
    it("f moves to the char; ; and , repeat", function()
      local ed = make("a.b.c")
      feed(ed, "f."); expect(ed.cx).to.equal(2)
      feed(ed, ";"); expect(ed.cx).to.equal(4)
      feed(ed, ","); expect(ed.cx).to.equal(2)
    end)
    it("t moves till before the char", function()
      local ed = make("xxx.y")
      feed(ed, "t."); expect(ed.cx).to.equal(3)
    end)
    it("F searches backward", function()
      local ed = make("a.b.c")
      feed(ed, "$F."); expect(ed.cx).to.equal(4)
    end)
    it("df deletes through the char (inclusive)", function()
      local ed = make("hello")
      feed(ed, "dfl"); expect(ed.buf:line(1)).to.equal("lo")
    end)
  end)

  describe("gg and marks", function()
    it("G then gg", function()
      local ed = make("a\nb\nc\nd")
      feed(ed, "G"); expect(ed.cy).to.equal(4)
      feed(ed, "gg"); expect(ed.cy).to.equal(1)
    end)
    it("dgg deletes to the first line (linewise)", function()
      local ed = make("a\nb\nc")
      feed(ed, "jdgg")                       -- from line 2, delete lines 1..2
      expect(ed.buf:get()).to.equal({ "c" })
    end)
    it("sets and jumps to a mark exactly (`)", function()
      local ed = make("hello\nworld")
      feed(ed, "ma"); feed(ed, "jl")
      expect(ed.cy).to.equal(2)
      feed(ed, "`a")
      expect(ed.cy).to.equal(1); expect(ed.cx).to.equal(1)
    end)
    it("'mark jumps to the mark's line", function()
      local ed = make("one\ntwo\nthree")
      feed(ed, "jma"); feed(ed, "G")         -- mark a at line 2, cursor to line 3
      feed(ed, "'a"); expect(ed.cy).to.equal(2)
    end)
  end)

  describe("UTF-8", function()
    local E = "\195\169" -- 'é', 2 bytes, 1 cell
    it("h and l move by character across multibyte", function()
      local ed = make("a" .. E .. "b")
      feed(ed, "l"); expect(ed.cx).to.equal(2)   -- onto é
      feed(ed, "l"); expect(ed.cx).to.equal(4)   -- skipped é's 2 bytes, onto b
      feed(ed, "h"); expect(ed.cx).to.equal(2)   -- back onto é
    end)
    it("x deletes a whole multibyte char", function()
      local ed = make("a" .. E .. "b")
      feed(ed, "lx")
      expect(ed.buf:line(1)).to.equal("ab")
    end)
    it("inserts a multibyte char typed as its bytes", function()
      local ed = make("ab")
      feed(ed, "i" .. E .. "\27")
      expect(ed.buf:line(1)).to.equal(E .. "ab")
    end)
  end)

  describe("| (goto column)", function()
    it("moves to a display column", function()
      local ed = make("abcdef")
      feed(ed, "4|"); expect(ed.cx).to.equal(4)
      feed(ed, "|"); expect(ed.cx).to.equal(1)   -- no count -> column 1
    end)
  end)

  describe("cword (word under cursor)", function()
    it("returns the word class run around the cursor, else empty", function()
      local ed = make("foo bar_baz, qux")
      ed.cx = 5;  expect(normal.cword(ed)).to.equal("bar_baz")  -- _ is a word char
      ed.cx = 1;  expect(normal.cword(ed)).to.equal("foo")
      ed.cx = 4;  expect(normal.cword(ed)).to.equal("")         -- on the space
      ed.cx = 12; expect(normal.cword(ed)).to.equal("")         -- on the comma
      ed.cx = 14; expect(normal.cword(ed)).to.equal("qux")
    end)
    it("captures a whole multibyte word", function()
      local ed = make("héllo wörld")
      ed.cx = 1; expect(normal.cword(ed)).to.equal("héllo")
    end)
  end)

  describe("gj / gk (screen-line motion)", function()
    it("gj == j when wrap is off", function()
      local ed = make("a\nb\nc")               -- no opts -> nowrap
      feed(ed, "gj"); expect(ed.cy).to.equal(2)
    end)
    it("gj/gk move by sub-row within a wrapped line", function()
      local ed = make("abcdefgh\nxyz")
      ed.opts = { wrap = true, tabstop = 8 }; ed.cols = 4  -- "abcdefgh" -> abcd/efgh
      feed(ed, "gj")                                       -- into the 2nd sub-row
      expect(ed.cy).to.equal(1); expect(ed.cx).to.equal(5) -- 'e'
      feed(ed, "gj")                                       -- across to the next line
      expect(ed.cy).to.equal(2); expect(ed.cx).to.equal(1)
      feed(ed, "gk")                                       -- back up one screen row
      expect(ed.cy).to.equal(1); expect(ed.cx).to.equal(5)
    end)
  end)

  describe("cross-line word motion", function()
    it("w crosses to the next line", function()
      local ed = make("foo\nbar")
      feed(ed, "w"); expect(ed.cy).to.equal(2); expect(ed.cx).to.equal(1)
    end)
    it("b crosses to the previous line", function()
      local ed = make("foo\nbar")
      feed(ed, "j0b"); expect(ed.cy).to.equal(1)
    end)
    it("dw on the last word of a line stops at the newline", function()
      local ed = make("foo\nbar")
      feed(ed, "dw"); expect(ed.buf:get()).to.equal({ "", "bar" })
    end)
  end)

  describe("operator + motion composition", function()
    it("dw deletes to the next word", function()
      local ed = make("foo bar")
      feed(ed, "dw")
      expect(ed.buf:line(1)).to.equal("bar")
      expect(ed.regs['"'].text).to.equal("foo ")
    end)
    it("d$ deletes to end of line (inclusive)", function()
      local ed = make("hello")
      feed(ed, "lld$")                            -- from col 3
      expect(ed.buf:line(1)).to.equal("he")
    end)
    it("dd / 2dd delete whole lines (linewise)", function()
      local ed = make("a\nb\nc\nd")
      feed(ed, "dd")
      expect(ed.buf:get()).to.equal({ "b", "c", "d" })
      feed(ed, "2dd")
      expect(ed.buf:get()).to.equal({ "d" })
      expect(ed.regs['"'].linewise).to.be(true)
    end)
  end)

  describe("edit + registers + put", function()
    it("x deletes the char under the cursor", function()
      local ed = make("abc")
      feed(ed, "x")
      expect(ed.buf:line(1)).to.equal("bc")
      expect(ed.regs['"'].text).to.equal("a")
    end)
    it("yy then p duplicates a line below", function()
      local ed = make("a\nb")
      feed(ed, "yyp")
      expect(ed.buf:get()).to.equal({ "a", "a", "b" })
      expect(ed.cy).to.equal(2)
    end)
    it("uses a named register", function()
      local ed = make("keep\ntoss")
      feed(ed, '"ayy')
      expect(ed.regs['a'].text).to.equal("keep\n")
      feed(ed, 'j"ap')                            -- put reg a below line 2
      expect(ed.buf:get()).to.equal({ "keep", "toss", "keep" })
    end)
  end)

  describe("insert mode", function()
    it("i inserts before the cursor", function()
      local ed = make("bc")
      feed(ed, "iA" .. ESC)
      expect(ed.buf:line(1)).to.equal("Abc")
      expect(ed.mode).to.equal("normal")
    end)
    it("a appends after the cursor", function()
      local ed = make("ac")
      feed(ed, "ab" .. ESC)
      expect(ed.buf:line(1)).to.equal("abc")
    end)
    it("o opens a line below and inserts", function()
      local ed = make("a\nc")
      feed(ed, "ob" .. ESC)
      expect(ed.buf:get()).to.equal({ "a", "b", "c" })
    end)
    it("<CR> in insert mode splits the line", function()
      local ed = make("ab")
      feed(ed, "i" .. "\r" .. ESC)
      expect(ed.buf:get()).to.equal({ "", "ab" })
    end)
    it("Ctrl-W erases the word before the cursor", function()
      local ed = make("")
      feed(ed, "ifoo bar\23" .. ESC)          -- type 'foo bar', Ctrl-W
      expect(ed.buf:line(1)).to.equal("foo ")
      feed(ed, "A baz qux\23" .. ESC)          -- again at end of line
      expect(ed.buf:line(1)).to.equal("foo  baz ")
    end)
    it("Ctrl-U erases from the cursor to the start of the line", function()
      local ed = make("")
      feed(ed, "ihello world\21" .. ESC)       -- type then Ctrl-U
      expect(ed.buf:line(1)).to.equal("")
    end)
    it("Ctrl-A / Ctrl-E jump to the line ends in insert mode", function()
      local ed = make("")
      feed(ed, "imiddle\1START")               -- Ctrl-A to bol, type
      feed(ed, "\5END" .. ESC)                  -- Ctrl-E to eol, type
      expect(ed.buf:line(1)).to.equal("STARTmiddleEND")
    end)
    it("cc changes a whole line", function()
      local ed = make("old\nkeep")
      feed(ed, "ccnew" .. ESC)
      expect(ed.buf:get()).to.equal({ "new", "keep" })
    end)
    it("records the last change for a future '.'", function()
      local ed = make("x")
      feed(ed, "iZ" .. ESC)
      expect(ed.last_change).to.exist()
    end)
  end)

  describe("r (replace char)", function()
    local CR = "\13"                          -- Enter in raw mode is carriage-return
    it("replaces the char under the cursor", function()
      local ed = make("hello")
      feed(ed, "rx")
      expect(ed.buf:line(1)).to.equal("xello")
    end)
    it("replaces count chars with a count", function()
      local ed = make("hello")
      feed(ed, "3rx")
      expect(ed.buf:line(1)).to.equal("xxxlo")
    end)
    it("errors (no-op) when fewer than count chars remain", function()
      local ed = make("hi")
      feed(ed, "5rx")
      expect(ed.buf:line(1)).to.equal("hi")
    end)
    -- The reported bug: r<CR> embedded a raw \r that broke rendering. It must
    -- split the line instead (POSIX), and no raw carriage-return may survive.
    it("r<CR> splits the line at the cursor", function()
      local ed = make("hello")
      feed(ed, "llr" .. CR)                    -- cursor on the first 'l'
      expect(ed.buf:get()).to.equal({ "he", "lo" })
      expect(ed.cy).to.equal(2)
      expect(ed.cx).to.equal(1)
      expect(ed.buf:line(1):find("\r")).to_not.exist()
      expect(ed.buf:line(2):find("\r")).to_not.exist()
    end)
    it("count r<CR> discards count chars, count-1 empty lines precede", function()
      local ed = make("hello")
      feed(ed, "ll2r" .. CR)
      expect(ed.buf:get()).to.equal({ "he", "", "o" })
      expect(ed.cy).to.equal(3)
    end)
    it("r<CR> at end of line leaves a trailing empty line", function()
      local ed = make("ab")
      feed(ed, "$r" .. CR)                      -- cursor on 'b' (last char)
      expect(ed.buf:get()).to.equal({ "a", "" })
    end)
    it("r<ESC> cancels with no change", function()
      local ed = make("hello")
      feed(ed, "lr" .. ESC)
      expect(ed.buf:line(1)).to.equal("hello")
    end)
    it("undoes a r<CR> split in one step", function()
      local ed = make("hello")
      feed(ed, "llr" .. CR)
      feed(ed, "u")
      expect(ed.buf:get()).to.equal({ "hello" })
    end)
  end)

  describe("'.' repeat", function()
    it("repeats the last change (delete)", function()
      local ed = make("abcde")
      feed(ed, "x")                       -- delete 'a' -> "bcde"
      feed(ed, ".")                       -- repeat -> "cde"
      expect(ed.buf:line(1)).to.equal("cde")
    end)
    it("repeats an insertion", function()
      local ed = make("Z")
      feed(ed, "ix" .. ESC)               -- "xZ", cursor on 'x'
      feed(ed, ".")                       -- insert 'x' again before cursor
      expect(ed.buf:line(1)).to.equal("xxZ")
    end)
  end)

  describe("maps", function()
    it("expands a leader map to its RHS", function()
      local ed = make("a\nb\nc")
      ex.dispatch(ed, "map \\d dd")            -- \d -> delete line
      feed(ed, "\\d")
      expect(ed.buf:get()).to.equal({ "b", "c" })
    end)
    it("is non-recursive (RHS keys are not re-mapped)", function()
      local ed = make("abc\ndef")
      ex.dispatch(ed, "map d x")                -- d -> x (delete char)
      ex.dispatch(ed, "map x dd")              -- x -> dd (should NOT fire from d's RHS)
      feed(ed, "d")
      expect(ed.buf:line(1)).to.equal("bc")    -- one char deleted, not the line
      expect(ed.buf:nlines()).to.equal(2)
    end)
    it("parses <...> notation and unmaps", function()
      local ed = make("hello")
      ex.dispatch(ed, "map <Space>x x")         -- <Space>x -> delete char (proves <Space> parse)
      feed(ed, " x")
      expect(ed.buf:line(1)).to.equal("ello")
      ex.dispatch(ed, "unmap <Space>x")
      expect(ed.maps[" x"]).to_not.exist()      -- map removed
    end)
    it("a map RHS can drive an ex command", function()
      local ed = make("x\ny\nz")
      ex.dispatch(ed, "map \\l :2d<CR>")        -- \l -> :2d
      feed(ed, "\\l")
      expect(ed.buf:get()).to.equal({ "x", "z" })
    end)
  end)

  describe("undo / redo", function()
    it("u undoes the last change; Ctrl-R redoes it", function()
      local ed = make("abc")
      feed(ed, "x"); expect(ed.buf:line(1)).to.equal("bc")
      feed(ed, "u"); expect(ed.buf:line(1)).to.equal("abc")
      feed(ed, "\18"); expect(ed.buf:line(1)).to.equal("bc")  -- Ctrl-R
    end)
    it("undoes a whole insert session as one change", function()
      local ed = make("x")
      feed(ed, "iAB" .. ESC); expect(ed.buf:line(1)).to.equal("ABx")
      feed(ed, "u"); expect(ed.buf:line(1)).to.equal("x")
    end)
    it("undoes commands one at a time", function()
      local ed = make("abc")
      feed(ed, "xx"); expect(ed.buf:line(1)).to.equal("c")
      feed(ed, "u"); expect(ed.buf:line(1)).to.equal("bc")
      feed(ed, "u"); expect(ed.buf:line(1)).to.equal("abc")
    end)
    it("undoes a dd", function()
      local ed = make("a\nb\nc")
      feed(ed, "dd"); expect(ed.buf:get()).to.equal({ "b", "c" })
      feed(ed, "u"); expect(ed.buf:get()).to.equal({ "a", "b", "c" })
    end)
    it("a status message survives until the next command's key", function()
      local ed = make("a")
      feed(ed, "u")                              -- nothing to undo -> sets a message
      expect(ed.message).to.equal("Already at oldest change")
      feed(ed, "j")                              -- next command clears it
      expect(ed.message).to_not.exist()
    end)
  end)

  describe("macros", function()
    it("records into a register and replays with @", function()
      local ed = make("a\nb\nc\nd")
      feed(ed, "qaddq")                    -- record 'dd' into reg a (deletes 'a')
      expect(ed.regs['a'].text).to.equal("dd")
      expect(ed.buf:get()).to.equal({ "b", "c", "d" })
      feed(ed, "@a")                       -- replay -> deletes 'b'
      expect(ed.buf:get()).to.equal({ "c", "d" })
    end)
    it("honors a count on @", function()
      local ed = make("1\n2\n3\n4\n5")
      feed(ed, "qxddq")                    -- reg x = 'dd', deletes '1'
      feed(ed, "2@x")                      -- delete two more lines
      expect(ed.buf:get()).to.equal({ "4", "5" })
    end)
    it("@@ repeats the last macro", function()
      local ed = make("1\n2\n3\n4")
      feed(ed, "qaddq")                    -- {2,3,4}
      feed(ed, "@a")                       -- {3,4}
      feed(ed, "@@")                       -- {4}
      expect(ed.buf:get()).to.equal({ "4" })
    end)
    it("records a multi-key edit macro", function()
      local ed = make("x\nx\nx")
      feed(ed, "qbA!" .. ESC .. "jq")      -- append '!' to a line, go down; reg b
      expect(ed.regs['b'].text).to.equal("A!" .. ESC .. "j")
      feed(ed, "@b@b")                      -- apply to the next two lines
      expect(ed.buf:get()).to.equal({ "x!", "x!", "x!" })
    end)
  end)

  describe(":normal send-keys", function()
    it("runs normal-mode keys given at the ':' prompt", function()
      local ed = make("foo bar")
      feed(ed, ":normal dw\r")            -- dw over the send-keys hatch
      expect(ed.buf:line(1)).to.equal("bar")
    end)
    it("leaves last_change set so '.' can repeat send-keys", function()
      local ed = make("one two three")
      feed(ed, ":normal dw\r")            -- "two three"
      feed(ed, ".")                       -- dw again -> "three"
      expect(ed.buf:line(1)).to.equal("three")
    end)
  end)

  describe("scrolling (Ctrl-F/B/D/U/E/Y)", function()
    -- A tall nowrap window: 100 short lines, rows=12 -> textrows=11, half=5,
    -- page=9 (11-2 overlap). One buffer line == one screen row, so top/cursor
    -- math is exact.
    local function tall()
      local t = {}
      for i = 1, 100 do t[i] = "line " .. i end
      local ed = make(table.concat(t, "\n"))
      ed.opts = { wrap = false, tabstop = 8 }
      ed.rows = 12
      return ed
    end
    local CF, CB, CD, CU, CE, CY = "\6", "\2", "\4", "\21", "\5", "\25"

    it("Ctrl-F/Ctrl-B page down and up (cursor keeps its screen row)", function()
      local ed = tall()
      feed(ed, CF); expect(ed.top).to.equal(10); expect(ed.cy).to.equal(10)
      feed(ed, CF); expect(ed.top).to.equal(19); expect(ed.cy).to.equal(19)
      feed(ed, CB); expect(ed.top).to.equal(10); expect(ed.cy).to.equal(10)
    end)

    it("Ctrl-D/Ctrl-U scroll half a page", function()
      local ed = tall()
      feed(ed, CD); expect(ed.top).to.equal(6);  expect(ed.cy).to.equal(6)
      feed(ed, CD); expect(ed.top).to.equal(11); expect(ed.cy).to.equal(11)
      feed(ed, CU); expect(ed.top).to.equal(6);  expect(ed.cy).to.equal(6)
    end)

    it("a count sets the scroll size for Ctrl-D", function()
      local ed = tall()
      feed(ed, "3" .. CD); expect(ed.top).to.equal(4); expect(ed.cy).to.equal(4)
    end)

    it("Ctrl-E reveals a lower line, keeping the cursor put until it scrolls off", function()
      local ed = tall()
      feed(ed, "4j"); expect(ed.cy).to.equal(5)     -- cursor mid-screen (row offset 4)
      feed(ed, CE); expect(ed.top).to.equal(2); expect(ed.cy).to.equal(5)  -- line kept
      feed(ed, CE .. CE .. CE)                       -- top climbs to the cursor's line
      expect(ed.top).to.equal(5); expect(ed.cy).to.equal(5)
      feed(ed, CE); expect(ed.top).to.equal(6); expect(ed.cy).to.equal(6)  -- now dragged
    end)

    it("Ctrl-Y reveals a higher line, keeping the cursor put mid-screen", function()
      local ed = tall()
      feed(ed, CD); expect(ed.top).to.equal(6); expect(ed.cy).to.equal(6) -- cursor on top row
      feed(ed, CY); expect(ed.top).to.equal(5); expect(ed.cy).to.equal(6) -- line kept, window up
    end)

    it("Ctrl-Y drags the cursor up when it sits on the bottom edge", function()
      local ed = tall()
      feed(ed, CD);       expect(ed.top).to.equal(6)  -- top=6
      feed(ed, "10j");    expect(ed.cy).to.equal(16)  -- cursor on the bottom row (offset 10)
      feed(ed, CY); expect(ed.top).to.equal(5); expect(ed.cy).to.equal(15) -- dragged up one
    end)

    it("does not scroll past the top of the buffer", function()
      local ed = tall()
      feed(ed, CB); expect(ed.top).to.equal(1); expect(ed.cy).to.equal(1)
      feed(ed, CY); expect(ed.top).to.equal(1)
    end)

    it("advances the sub-row when the top line wraps (wrap mode)", function()
      local long = string.rep("x", 200)            -- 200 cols / W=80 -> 3 sub-rows
      local ed = make(long .. "\na\nb\nc")
      ed.opts = { wrap = true, tabstop = 8 }
      ed.rows = 12; ed.cols = 80; ed.top = 1; ed.topsub = 0
      feed(ed, "\5")                                -- Ctrl-E: reveal one screen row
      expect(ed.top).to.equal(1); expect(ed.topsub).to.equal(1)
    end)
  end)

  describe("derived edit commands D C Y s S X J ~", function()
    it("D deletes from the cursor to end-of-line", function()
      local ed = make("hello world")
      feed(ed, "6lD")
      expect(ed.buf:line(1)).to.equal("hello ")
      expect(ed.regs['"'].text).to.equal("world")
    end)
    it("2D deletes to EOL plus the whole next line", function()
      local ed = make("abcdef\nghijkl\nmnop")
      feed(ed, "3l2D")
      expect(ed.buf:get()).to.equal({ "abc", "mnop" })
    end)
    it("C changes to end-of-line and enters insert", function()
      local ed = make("hello world")
      feed(ed, "6lCthere" .. ESC)
      expect(ed.buf:line(1)).to.equal("hello there")
      expect(ed.mode).to.equal("normal")
    end)
    it("Y yanks the current line linewise; 2Y yanks two", function()
      local ed = make("one\ntwo\nthree")
      feed(ed, "Y")
      expect(ed.regs['"'].text).to.equal("one\n")
      expect(ed.regs['"'].linewise).to.be(true)
      feed(ed, "2Y")
      expect(ed.regs['"'].text).to.equal("one\ntwo\n")
    end)
    it("s substitutes count chars and enters insert", function()
      local ed = make("hello")
      feed(ed, "2sXY" .. ESC)
      expect(ed.buf:line(1)).to.equal("XYllo")
    end)
    it("s on an empty line still enters insert", function()
      local ed = make("")
      feed(ed, "shi" .. ESC)
      expect(ed.buf:line(1)).to.equal("hi")
    end)
    it("S changes the whole line", function()
      local ed = make("hello\nworld")
      feed(ed, "Snew" .. ESC)
      expect(ed.buf:get()).to.equal({ "new", "world" })
    end)
    it("X deletes the char before the cursor", function()
      local ed = make("hello")
      feed(ed, "3lX")     -- cursor on 'l' (col 4); delete the char before it
      expect(ed.buf:line(1)).to.equal("helo")
      expect(ed.cx).to.equal(3)
    end)
    it("X is a no-op at column 1", function()
      local ed = make("hello")
      feed(ed, "X")
      expect(ed.buf:line(1)).to.equal("hello")
    end)
    it("J joins lines with a separating space", function()
      local ed = make("foo\nbar")
      feed(ed, "J")
      expect(ed.buf:line(1)).to.equal("foo bar")
      expect(ed.cx).to.equal(4)   -- on the join space
    end)
    it("J strips leading blanks and skips the space before ')'", function()
      local ed = make("foo\n   bar")
      feed(ed, "J")
      expect(ed.buf:line(1)).to.equal("foo bar")
      local ed2 = make("foo\n)bar")
      feed(ed2, "J")
      expect(ed2.buf:line(1)).to.equal("foo)bar")
    end)
    it("3J joins three lines", function()
      local ed = make("a\nb\nc\nd")
      feed(ed, "3J")
      expect(ed.buf:get()).to.equal({ "a b c", "d" })
    end)
    it("~ toggles case and advances", function()
      local ed = make("aB.c")
      feed(ed, "~")
      expect(ed.buf:line(1)).to.equal("AB.c")
      expect(ed.cx).to.equal(2)
      feed(ed, "~")
      expect(ed.buf:line(1)).to.equal("Ab.c")
    end)
    it("3~ toggles a run", function()
      local ed = make("abcd")
      feed(ed, "3~")
      expect(ed.buf:line(1)).to.equal("ABCd")
      expect(ed.cx).to.equal(4)
    end)
    it("D and . repeat", function()
      local ed = make("abcXdef\nabcYdef")
      feed(ed, "3lD")
      expect(ed.buf:line(1)).to.equal("abc")
      feed(ed, "j0.")
      expect(ed.buf:line(2)).to.equal("")
    end)
  end)

  describe("paragraph motions { }", function()
    -- 1:p1a 2:p1b 3:"" 4:p2a 5:p2b 6:"" 7:p3
    local function paras() return make("p1a\np1b\n\np2a\np2b\n\np3") end
    it("} moves forward to the next empty line, then EOF", function()
      local ed = paras()
      feed(ed, "}"); expect(ed.cy).to.equal(3)
      feed(ed, "}"); expect(ed.cy).to.equal(6)
      feed(ed, "}"); expect(ed.cy).to.equal(7)   -- last line
    end)
    it("{ moves backward to the previous empty line, then BOF", function()
      local ed = paras()
      feed(ed, "G");  expect(ed.cy).to.equal(7)
      feed(ed, "{");  expect(ed.cy).to.equal(6)
      feed(ed, "{");  expect(ed.cy).to.equal(3)
      feed(ed, "{");  expect(ed.cy).to.equal(1)
    end)
    it("honors a count", function()
      local ed = paras()
      feed(ed, "2}"); expect(ed.cy).to.equal(6)
    end)
    it("lands on column 1 of the boundary", function()
      local ed = paras()
      feed(ed, "ll}"); expect(ed.cx).to.equal(1)
    end)
    it("d} deletes charwise up to the boundary", function()
      local ed = make("abc\ndef\n\nxyz")
      feed(ed, "ld}")   -- from (1,2) exclusive to the blank line
      expect(ed.buf:get()).to.equal({ "a", "", "xyz" })
    end)
  end)

  describe("section motions [[ ]]", function()
    -- 1:{ 2:foo 3:bar 4:{ 5:baz
    local function secs() return make("{\nfoo\nbar\n{\nbaz") end
    it("]] moves forward to the next section boundary, then EOF", function()
      local ed = secs()
      feed(ed, "]]"); expect(ed.cy).to.equal(4)
      feed(ed, "]]"); expect(ed.cy).to.equal(5)
    end)
    it("[[ moves backward to the previous section boundary", function()
      local ed = secs()
      feed(ed, "G");   expect(ed.cy).to.equal(5)
      feed(ed, "[[");  expect(ed.cy).to.equal(4)
      feed(ed, "[[");  expect(ed.cy).to.equal(1)
    end)
    it("]] ignores empty lines (only sections)", function()
      local ed = make("a\n\nb\n{\nc")   -- blank line 2 is NOT a section boundary
      feed(ed, "]]"); expect(ed.cy).to.equal(4)
    end)
    it("a lone ] is a no-op (waits for the pair, discards the key)", function()
      local ed = secs()
      feed(ed, "]x"); expect(ed.cy).to.equal(1)  -- ']' then 'x' -> no move
    end)
    it("d]] deletes to the next section boundary", function()
      local ed = make("foo\nbar\n{\nbaz")
      feed(ed, "ld]]")   -- from (1,2) to the '{' line, exclusive
      expect(ed.buf:get()).to.equal({ "f", "{", "baz" })
    end)
  end)

  describe("shift operators < >", function()
    it(">> indents by shiftwidth, tab-optimized by default", function()
      local ed = make("foo\nbar")
      feed(ed, ">>")                       -- default sw=8, ts=8, noexpandtab
      expect(ed.buf:line(1)).to.equal("\tfoo")
      expect(ed.cx).to.equal(2)            -- first non-blank
    end)
    it("<< removes a level of indent", function()
      local ed = make("\tfoo")
      feed(ed, "<<")
      expect(ed.buf:line(1)).to.equal("foo")
    end)
    it("respects :set shiftwidth and expandtab", function()
      local ed = make("foo")
      feed(ed, ":set sw=2 expandtab\r")
      feed(ed, ">>")
      expect(ed.buf:line(1)).to.equal("  foo")
      feed(ed, ">>")
      expect(ed.buf:line(1)).to.equal("    foo")
    end)
    it("2>> shifts a count of lines", function()
      local ed = make("a\nb\nc")
      feed(ed, ":set sw=2 et\r")
      feed(ed, "2>>")
      expect(ed.buf:get()).to.equal({ "  a", "  b", "c" })
    end)
    it(">j shifts the lines a motion spans", function()
      local ed = make("a\nb\nc")
      feed(ed, ":set sw=2 et\r")
      feed(ed, ">j")
      expect(ed.buf:get()).to.equal({ "  a", "  b", "c" })
    end)
    it("leaves an empty line unchanged on right shift", function()
      local ed = make("foo\n\nbar")
      feed(ed, ":set sw=2 et\r")
      feed(ed, "2>j")   -- shift 3 lines (current + 2 down)
      expect(ed.buf:get()).to.equal({ "  foo", "", "  bar" })
    end)
    it("a whole multi-line shift undoes as one change", function()
      local ed = make("a\nb\nc")
      feed(ed, ":set sw=2 et\r")
      feed(ed, "2>>")
      feed(ed, "u")
      expect(ed.buf:get()).to.equal({ "a", "b", "c" })
    end)
  end)

  describe("R (replace/overwrite mode)", function()
    it("overwrites characters in place", function()
      local ed = make("hello")
      feed(ed, "RXYZ" .. ESC)
      expect(ed.buf:line(1)).to.equal("XYZlo")
    end)
    it("extends the line when typing past end-of-line", function()
      local ed = make("ab")
      feed(ed, "RXYZW" .. ESC)
      expect(ed.buf:line(1)).to.equal("XYZW")
    end)
    it("backspace moves left without restoring", function()
      local ed = make("hello")
      feed(ed, "RXY\127Z" .. ESC)   -- type XY, backspace over Y, type Z
      expect(ed.buf:line(1)).to.equal("XZllo")
    end)
    it("leaves the cursor stepped back on <Esc>, like insert", function()
      local ed = make("hello")
      feed(ed, "RAB" .. ESC)
      expect(ed.buf:line(1)).to.equal("ABllo")
      expect(ed.cx).to.equal(2)
      expect(ed.mode).to.equal("normal")
    end)
    it("is repeatable with .", function()
      local ed = make("aaaa\nbbbb")
      feed(ed, "RXX" .. ESC)
      expect(ed.buf:line(1)).to.equal("XXaa")
      feed(ed, "j0.")
      expect(ed.buf:line(2)).to.equal("XXbb")
    end)
  end)

  describe("screen-position motions H M L", function()
    local function tall()
      local lines = {}
      for i = 1, 30 do lines[i] = "line" .. i end
      local ed = make(table.concat(lines, "\n"))
      ed.rows = 11; ed.top = 5   -- textrows = 10, showing lines 5..14
      return ed
    end
    it("H goes to the top of the screen (+count)", function()
      local ed = tall()
      feed(ed, "H");  expect(ed.cy).to.equal(5)
      feed(ed, "3H"); expect(ed.cy).to.equal(7)
    end)
    it("L goes to the bottom of the screen (-count)", function()
      local ed = tall()
      feed(ed, "L");  expect(ed.cy).to.equal(14)
      feed(ed, "2L"); expect(ed.cy).to.equal(13)
    end)
    it("M goes to the middle of the screen", function()
      local ed = tall()
      feed(ed, "M"); expect(ed.cy).to.equal(9)   -- (5 + 14) / 2
    end)
    it("dH deletes linewise up to the top of the screen", function()
      local ed = tall()
      feed(ed, "7GdH")   -- from line 7 up to top (line 5): delete 5,6,7
      expect(ed.buf:line(5)).to.equal("line8")
    end)
  end)

  describe("z reposition and Ctrl-G", function()
    local function tall()
      local lines = {}
      for i = 1, 30 do lines[i] = "L" .. i end
      local ed = make(table.concat(lines, "\n"))
      ed.rows = 11   -- textrows = 10
      return ed
    end
    it("z<CR> puts the current line at the top", function()
      local ed = tall()
      feed(ed, "15G"); feed(ed, "z\r")
      expect(ed.top).to.equal(15); expect(ed.cy).to.equal(15)
    end)
    it("z. centers the current line", function()
      local ed = tall()
      feed(ed, "15Gz.")
      expect(ed.top).to.equal(10)  -- 15 - floor(10/2)
    end)
    it("z- puts the current line at the bottom", function()
      local ed = tall()
      feed(ed, "15Gz-")
      expect(ed.top).to.equal(6)   -- 15 - (10 - 1)
    end)
    it("[count]z<CR> repositions around a given line", function()
      local ed = tall()
      feed(ed, "20z\r")
      expect(ed.top).to.equal(20); expect(ed.cy).to.equal(20)
    end)
    it("Ctrl-G reports file position on the message line", function()
      local ed = tall()
      feed(ed, "15G\7")
      expect(ed.message).to.exist()
      expect(ed.message:find("line 15 of 30", 1, true)).to.exist()
    end)
  end)

  describe("ZZ / ZQ", function()
    it("ZQ quits without writing", function()
      local ed = make("dirty")
      feed(ed, "x")                 -- make it modified
      expect(ed.buf.modified).to.be(true)
      feed(ed, "ZQ")
      expect(ed.running).to.be(false)
    end)
    it("ZZ on an unnamed buffer errors instead of quitting", function()
      local ed = make("hello")
      feed(ed, "ZZ")
      expect(ed.running).to.be(true)
      expect(ed.message).to.exist()
    end)
  end)

  describe("the ':' prompt shares ex.dispatch", function()
    it("runs an ex command typed at ':'", function()
      local ed = make("a\nb\nc")
      feed(ed, ":2d\r")
      expect(ed.buf:get()).to.equal({ "a", "c" })
      expect(ed.mode).to.equal("normal")
    end)
    it(":q sets running=false", function()
      local ed = make("a")
      feed(ed, ":q\r")
      expect(ed.running).to.be(false)
    end)
  end)
end)

os.exit(lust.errors == 0 and 0 or 1)
