-- Tests for normal.lua (the coroutine interpreter). Run: luajit test/normal_test.lua
package.path = "vendor/lust/?.lua;./?.lua;" .. package.path

local lust   = require("lust")
local buffer = require("buffer")
local normal = require("normal")
local editor = require("editor")
local ex     = require("ex")
local sys    = require("sys")
local describe, it, expect = lust.describe, lust.it, lust.expect

-- Build an editor state with a live interpreter coroutine, primed to getkey.
local function make(text)
  local ed = editor.new_ed()
  ed.buf = buffer.new(text)
  ed.interp = coroutine.create(function() normal.loop(ed) end)
  assert(coroutine.resume(ed.interp))
  return ed
end

-- Feed a string of keys and let the coroutine drain them.
local function feed(ed, s)
  for i = 1, #s do ed.inject[#ed.inject + 1] = s:byte(i) end
  assert(coroutine.resume(ed.interp))
  return ed
end

local ESC = "\27"

describe("normal-mode interpreter", function()
  describe("motions", function()
    it("h j k l 0 $ move the cursor", function()
      local ed = make("abc\ndef")
      feed(ed, "ll"); expect(ed.cx).to.equal(3)
      feed(ed, "0");  expect(ed.cx).to.equal(1)
      feed(ed, "$");  expect(ed.cx).to.equal(3)
      feed(ed, "j");  expect(ed.cy).to.equal(2)
      feed(ed, "k");  expect(ed.cy).to.equal(1)
    end)
    it("honors a count", function()
      local ed = make("abcdef")
      feed(ed, "3l"); expect(ed.cx).to.equal(4)
    end)
    it("G goes to a line or the last line", function()
      local ed = make("a\nb\nc\nd")
      feed(ed, "G");  expect(ed.cy).to.equal(4)
      feed(ed, "2G"); expect(ed.cy).to.equal(2)
    end)
    it("w b e move by word within a line", function()
      local ed = make("foo bar baz")
      feed(ed, "w"); expect(ed.cx).to.equal(5)   -- start of 'bar'
      feed(ed, "e"); expect(ed.cx).to.equal(7)   -- end of 'bar'
      feed(ed, "b"); expect(ed.cx).to.equal(5)   -- back to start of 'bar'
    end)
  end)

  describe("find motions f t F T ; ,", function()
    it("f moves to the char; ; and , repeat", function()
      local ed = make("a.b.c")
      feed(ed, "f."); expect(ed.cx).to.equal(2)
      feed(ed, ";"); expect(ed.cx).to.equal(4)
      feed(ed, ","); expect(ed.cx).to.equal(2)
    end)
    it("t moves till before the char", function()
      local ed = make("xxx.y")
      feed(ed, "t."); expect(ed.cx).to.equal(3)
    end)
    it("F searches backward", function()
      local ed = make("a.b.c")
      feed(ed, "$F."); expect(ed.cx).to.equal(4)
    end)
    it("df deletes through the char (inclusive)", function()
      local ed = make("hello")
      feed(ed, "dfl"); expect(ed.buf:line(1)).to.equal("lo")
    end)
  end)

  describe("gg and marks", function()
    it("G then gg", function()
      local ed = make("a\nb\nc\nd")
      feed(ed, "G"); expect(ed.cy).to.equal(4)
      feed(ed, "gg"); expect(ed.cy).to.equal(1)
    end)
    it("dgg deletes to the first line (linewise)", function()
      local ed = make("a\nb\nc")
      feed(ed, "jdgg")                       -- from line 2, delete lines 1..2
      expect(ed.buf:get()).to.equal({ "c" })
    end)
    it("sets and jumps to a mark exactly (`)", function()
      local ed = make("hello\nworld")
      feed(ed, "ma"); feed(ed, "jl")
      expect(ed.cy).to.equal(2)
      feed(ed, "`a")
      expect(ed.cy).to.equal(1); expect(ed.cx).to.equal(1)
    end)
    it("'mark jumps to the mark's line", function()
      local ed = make("one\ntwo\nthree")
      feed(ed, "jma"); feed(ed, "G")         -- mark a at line 2, cursor to line 3
      feed(ed, "'a"); expect(ed.cy).to.equal(2)
    end)
  end)

  describe("UTF-8", function()
    local E = "\195\169" -- 'é', 2 bytes, 1 cell
    it("h and l move by character across multibyte", function()
      local ed = make("a" .. E .. "b")
      feed(ed, "l"); expect(ed.cx).to.equal(2)   -- onto é
      feed(ed, "l"); expect(ed.cx).to.equal(4)   -- skipped é's 2 bytes, onto b
      feed(ed, "h"); expect(ed.cx).to.equal(2)   -- back onto é
    end)
    it("x deletes a whole multibyte char", function()
      local ed = make("a" .. E .. "b")
      feed(ed, "lx")
      expect(ed.buf:line(1)).to.equal("ab")
    end)
    it("inserts a multibyte char typed as its bytes", function()
      local ed = make("ab")
      feed(ed, "i" .. E .. "\27")
      expect(ed.buf:line(1)).to.equal(E .. "ab")
    end)
  end)

  describe("| (goto column)", function()
    it("moves to a display column", function()
      local ed = make("abcdef")
      feed(ed, "4|"); expect(ed.cx).to.equal(4)
      feed(ed, "|"); expect(ed.cx).to.equal(1)   -- no count -> column 1
    end)
  end)

  describe("cword (word under cursor)", function()
    it("returns the word class run around the cursor, else empty", function()
      local ed = make("foo bar_baz, qux")
      ed.cx = 5;  expect(normal.cword(ed)).to.equal("bar_baz")  -- _ is a word char
      ed.cx = 1;  expect(normal.cword(ed)).to.equal("foo")
      ed.cx = 4;  expect(normal.cword(ed)).to.equal("")         -- on the space
      ed.cx = 12; expect(normal.cword(ed)).to.equal("")         -- on the comma
      ed.cx = 14; expect(normal.cword(ed)).to.equal("qux")
    end)
    it("captures a whole multibyte word", function()
      local ed = make("héllo wörld")
      ed.cx = 1; expect(normal.cword(ed)).to.equal("héllo")
    end)
  end)

  describe("gj / gk (screen-line motion)", function()
    it("gj == j when wrap is off", function()
      local ed = make("a\nb\nc")               -- no opts -> nowrap
      feed(ed, "gj"); expect(ed.cy).to.equal(2)
    end)
    it("gj/gk move by sub-row within a wrapped line", function()
      local ed = make("abcdefgh\nxyz")
      ed.opts = { wrap = true, tabstop = 8 }; ed.cols = 4  -- "abcdefgh" -> abcd/efgh
      feed(ed, "gj")                                       -- into the 2nd sub-row
      expect(ed.cy).to.equal(1); expect(ed.cx).to.equal(5) -- 'e'
      feed(ed, "gj")                                       -- across to the next line
      expect(ed.cy).to.equal(2); expect(ed.cx).to.equal(1)
      feed(ed, "gk")                                       -- back up one screen row
      expect(ed.cy).to.equal(1); expect(ed.cx).to.equal(5)
    end)
  end)

  describe("cross-line word motion", function()
    it("w crosses to the next line", function()
      local ed = make("foo\nbar")
      feed(ed, "w"); expect(ed.cy).to.equal(2); expect(ed.cx).to.equal(1)
    end)
    it("b crosses to the previous line", function()
      local ed = make("foo\nbar")
      feed(ed, "j0b"); expect(ed.cy).to.equal(1)
    end)
    it("dw on the last word of a line stops at the newline", function()
      local ed = make("foo\nbar")
      feed(ed, "dw"); expect(ed.buf:get()).to.equal({ "", "bar" })
    end)
  end)

  describe("operator + motion composition", function()
    it("dw deletes to the next word", function()
      local ed = make("foo bar")
      feed(ed, "dw")
      expect(ed.buf:line(1)).to.equal("bar")
      expect(ed.regs['"'].text).to.equal("foo ")
    end)
    it("d$ deletes to end of line (inclusive)", function()
      local ed = make("hello")
      feed(ed, "lld$")                            -- from col 3
      expect(ed.buf:line(1)).to.equal("he")
    end)
    it("dd / 2dd delete whole lines (linewise)", function()
      local ed = make("a\nb\nc\nd")
      feed(ed, "dd")
      expect(ed.buf:get()).to.equal({ "b", "c", "d" })
      feed(ed, "2dd")
      expect(ed.buf:get()).to.equal({ "d" })
      expect(ed.regs['"'].linewise).to.be(true)
    end)
  end)

  describe("text objects", function()
    it("diw deletes the word under the cursor (from within)", function()
      local ed = make("foo bar baz")
      feed(ed, "wdiw")                              -- cursor on 'bar'
      expect(ed.buf:line(1)).to.equal("foo  baz")
      expect(ed.regs['"'].text).to.equal("bar")
    end)
    it("daw includes the trailing blank", function()
      local ed = make("foo bar baz")
      feed(ed, "wdaw")
      expect(ed.buf:line(1)).to.equal("foo baz")
    end)
    it("daw on the last word takes the leading blank instead", function()
      local ed = make("foo bar")
      feed(ed, "wdaw")                              -- no trailing blank -> leading
      expect(ed.buf:line(1)).to.equal("foo")
    end)
    it("diw on whitespace deletes the blank run", function()
      local ed = make("foo   bar")
      feed(ed, "llldiw")                            -- cursor on first space
      expect(ed.buf:line(1)).to.equal("foobar")
    end)
    it("daw on whitespace adds the following word", function()
      local ed = make("foo   bar baz")
      feed(ed, "llldaw")
      expect(ed.buf:line(1)).to.equal("foo baz")
    end)
    it("ciw replaces the word and leaves insert applied", function()
      local ed = make("foo bar")
      feed(ed, "wciwX" .. ESC)
      expect(ed.buf:line(1)).to.equal("foo X")
    end)
    it("diW treats punctuation as part of the WORD", function()
      local ed = make("foo.bar baz")
      feed(ed, "diW")
      expect(ed.buf:line(1)).to.equal(" baz")
      expect(ed.regs['"'].text).to.equal("foo.bar")
    end)
    it("di( / da( from inside the parens", function()
      local ed = make("a(bcd)e")
      feed(ed, "lldi(")                             -- cursor on 'b'
      expect(ed.buf:line(1)).to.equal("a()e")
      local ed2 = make("a(bcd)e")
      feed(ed2, "llda(")
      expect(ed2.buf:line(1)).to.equal("ae")
    end)
    it("di( works with the cursor on either bracket", function()
      local ed = make("a(bcd)e")
      feed(ed, "ldi(")                              -- on '('
      expect(ed.buf:line(1)).to.equal("a()e")
      local ed2 = make("a(bcd)e")
      feed(ed2, "5ldi(")                            -- on ')'
      expect(ed2.buf:line(1)).to.equal("a()e")
    end)
    it("di{ picks the innermost enclosing pair", function()
      local ed = make("{a{b}c}")
      feed(ed, "3ldi{")                             -- cursor on 'b'
      expect(ed.buf:line(1)).to.equal("{a{}c}")
    end)
    it("ci( on empty parens opens insert between them", function()
      local ed = make("f()")
      feed(ed, "lci(X" .. ESC)                      -- cursor on '('
      expect(ed.buf:line(1)).to.equal("f(X)")
    end)
    it("di( spanning lines splices the inner range", function()
      local ed = make("foo(\nbar\n)baz")
      feed(ed, "3ldi(")                             -- on '(' at col 4
      expect(ed.buf:get()).to.equal({ "foo()baz" })
    end)
    it("di\" / da\" operate on the quoted string", function()
      local ed = make('say "hi" ok')
      feed(ed, '5ldi"')                             -- cursor inside the quotes
      expect(ed.buf:line(1)).to.equal('say "" ok')
      local ed2 = make('say "hi" ok')
      feed(ed2, '5lda"')                            -- + trailing blank
      expect(ed2.buf:line(1)).to.equal("say ok")
    end)
    it("ci\" before a string operates on the next pair", function()
      local ed = make('x "ab"')
      feed(ed, 'ci"Z' .. ESC)                       -- cursor at col 1, before the pair
      expect(ed.buf:line(1)).to.equal('x "Z"')
    end)
    it("dip / dap operate linewise on the paragraph", function()
      local ed = make("a\nb\n\nc")
      feed(ed, "dip")
      expect(ed.buf:get()).to.equal({ "", "c" })
      expect(ed.regs['"'].linewise).to.be(true)
      local ed2 = make("a\nb\n\nc")
      feed(ed2, "dap")                              -- + the trailing blank line
      expect(ed2.buf:get()).to.equal({ "c" })
    end)
    it("a failed object is a clean no-op (no insert, no change)", function()
      local ed = make("hello")
      feed(ed, "ci(")                               -- no parens on the line
      expect(ed.mode).to.equal("normal")            -- did NOT fall into insert
      feed(ed, "x")                                 -- next command still normal-mode
      expect(ed.buf:line(1)).to.equal("ello")
    end)
    it(". repeats a text-object change at the new cursor", function()
      local ed = make("foo bar baz qux")
      feed(ed, "daw")                               -- delete 'foo '
      expect(ed.buf:line(1)).to.equal("bar baz qux")
      feed(ed, ".")                                 -- repeat -> delete 'bar '
      expect(ed.buf:line(1)).to.equal("baz qux")
    end)
  end)

  describe("custom text objects (:textobj filter)", function()
    it("applies a charwise range from the filter's stdout", function()
      local ed = make("hello")
      ex.dispatch(ed, [[textobj z sh -c 'printf "char 1 1 1 3\n"']])
      feed(ed, "diz")                               -- filter says cols 1..3
      expect(ed.buf:line(1)).to.equal("lo")
    end)
    it("applies a linewise range", function()
      local ed = make("a\nb\nc")
      ex.dispatch(ed, [[textobj z sh -c 'printf "line 1 2\n"']])
      feed(ed, "diz")
      expect(ed.buf:get()).to.equal({ "c" })
      expect(ed.regs['"'].linewise).to.be(true)
    end)
    it("c on a custom object enters insert (proves the coroutine path)", function()
      local ed = make("hello")
      ex.dispatch(ed, [[textobj z sh -c 'printf "char 1 1 1 3\n"']])
      feed(ed, "cizXY" .. ESC)                      -- delete cols 1..3, then type
      expect(ed.buf:line(1)).to.equal("XYlo")
    end)
    it("empty filter output is a clean no-op (no change, no insert)", function()
      local ed = make("hello")
      ex.dispatch(ed, [[textobj z sh -c ':']])      -- prints nothing
      feed(ed, "diz")
      expect(ed.mode).to.equal("normal")
      feed(ed, "x"); expect(ed.buf:line(1)).to.equal("ello")
    end)
    it("a builtin object always wins over a registered key", function()
      local ed = make("foo bar")
      ex.dispatch(ed, [[textobj w sh -c 'printf "char 1 1 1 5\n"']])
      feed(ed, "diw")                               -- builtin word, NOT the filter
      expect(ed.buf:line(1)).to.equal(" bar")
    end)
    it("textobj KEY with no command unregisters it", function()
      local ed = make("hello")
      ex.dispatch(ed, [[textobj z sh -c 'printf "char 1 1 1 3\n"']])
      ex.dispatch(ed, "textobj z")                  -- clear
      feed(ed, "diz")
      expect(ed.buf:line(1)).to.equal("hello")      -- z now unhandled: no-op
    end)
    -- End-to-end with the shipped contrib/lvi-textobj-tag (assumes repo-root cwd,
    -- which `make test` and a direct `luajit test/...` both use). Proves the
    -- script's stdout format matches what ex.textobj_range parses.
    it("contrib/lvi-textobj-tag drives dit / cit", function()
      local ed = make("<p>hello</p>")
      ex.dispatch(ed, "textobj t contrib/lvi-textobj-tag")
      feed(ed, "4ldit")                             -- cursor inside 'hello'
      expect(ed.buf:line(1)).to.equal("<p></p>")
      local ed2 = make("<p>hello</p>")
      ex.dispatch(ed2, "textobj t contrib/lvi-textobj-tag")
      feed(ed2, "4lcitHi" .. ESC)                   -- change inner, type "Hi"
      expect(ed2.buf:line(1)).to.equal("<p>Hi</p>")
    end)
  end)

  describe("case operators (gu / gU / g~)", function()
    it("gUiw uppercases the word", function()
      local ed = make("foo bar")
      feed(ed, "gUiw"); expect(ed.buf:line(1)).to.equal("FOO bar")
    end)
    it("guiw lowercases the word", function()
      local ed = make("FOO BAR")
      feed(ed, "guiw"); expect(ed.buf:line(1)).to.equal("foo BAR")
    end)
    it("g~iw toggles case", function()
      local ed = make("FoO bar")
      feed(ed, "g~iw"); expect(ed.buf:line(1)).to.equal("fOo bar")
    end)
    it("gU$ works over a charwise motion from the cursor", function()
      local ed = make("foo bar")
      feed(ed, "wgU$"); expect(ed.buf:line(1)).to.equal("foo BAR")
    end)
    it("gUU uppercases the whole current line", function()
      local ed = make("hi there")
      feed(ed, "gUU"); expect(ed.buf:line(1)).to.equal("HI THERE")
    end)
    it("gUip uppercases a whole paragraph (multi-line)", function()
      local ed = make("foo\nbar\n\nx")
      feed(ed, "gUip"); expect(ed.buf:get()).to.equal({ "FOO", "BAR", "", "x" })
    end)
    it("gg still works as a motion (g namespace intact)", function()
      local ed = make("a\nb\nc")
      feed(ed, "G");  expect(ed.cy).to.equal(3)
      feed(ed, "gg"); expect(ed.cy).to.equal(1)
    end)
    it("dgg still deletes to the first line (operator + g motion)", function()
      local ed = make("a\nb\nc")
      feed(ed, "Gdgg"); expect(ed.buf:get()).to.equal({ "" })
    end)
  end)

  describe("! filter operator and gq", function()
    it("! seeds the prompt with the motion's line range and filters", function()
      local ed = make("charlie\nalpha\nbravo")
      feed(ed, "!Gsort\r")                          -- filter lines 1..3 through sort
      expect(ed.buf:get()).to.equal({ "alpha", "bravo", "charlie" })
    end)
    it("!! filters the current line", function()
      local ed = make("hello\nworld")
      feed(ed, "!!tr a-z A-Z\r")
      expect(ed.buf:get()).to.equal({ "HELLO", "world" })
    end)
    it("cancelling the ! prompt leaves the buffer unchanged", function()
      local ed = make("b\na")
      feed(ed, "!Gsort\27")                          -- Esc cancels
      expect(ed.buf:get()).to.equal({ "b", "a" })
    end)
    it("gq filters a paragraph through $LVI_FMT", function()
      sys.setenv("LVI_FMT", "tr a-z A-Z")
      local ed = make("foo\nbar\n\nbaz")
      feed(ed, "gqip"); expect(ed.buf:get()).to.equal({ "FOO", "BAR", "", "baz" })
    end)
    it(". repeats gq on the next paragraph", function()
      sys.setenv("LVI_FMT", "tr a-z A-Z")
      local ed = make("foo\n\nbar")
      feed(ed, "gqip"); expect(ed.buf:line(1)).to.equal("FOO")
      feed(ed, "G.");   expect(ed.buf:line(3)).to.equal("BAR")
    end)
  end)

  describe("insert-mode Tab and expandtab", function()
    it("inserts a literal tab by default", function()
      local ed = make("x")
      feed(ed, "A\t\27")
      expect(ed.buf:line(1)).to.equal("x\t")
    end)
    it("expands to spaces by one shiftwidth when expandtab is on", function()
      local ed = make("")
      ex.dispatch(ed, "set et sw=4")                  -- shiftwidth, not tabstop, is the indent unit
      feed(ed, "i\t\27")                              -- from col 1
      expect(ed.buf:line(1)).to.equal("    ")         -- 4 spaces
    end)
    it("is column-aware: fills only to the next shiftwidth boundary", function()
      local ed = make("ab")
      ex.dispatch(ed, "set et sw=4")
      feed(ed, "A\t\27")                              -- cursor at display col 2 -> 2 spaces
      expect(ed.buf:line(1)).to.equal("ab  ")
    end)
    it("uses shiftwidth even when tabstop differs", function()
      local ed = make("")
      ex.dispatch(ed, "set et sw=4 ts=8")             -- the exact ~/.lvirc case
      feed(ed, "i\t\27")
      expect(ed.buf:line(1)).to.equal("    ")         -- 4 (sw), not 8 (ts)
    end)
    it("with autoindent, indentation propagates as spaces", function()
      local ed = make("")
      ex.dispatch(ed, "set et sw=4 ai")
      feed(ed, "i\tfoo\rbar\27")                      -- tab->spaces, then <CR> carries them
      expect(ed.buf:get()).to.equal({ "    foo", "    bar" })
    end)
  end)

  describe("autoindent", function()
    it("is off by default: o does not carry indent", function()
      local ed = make("    hello")
      feed(ed, "obar\27")
      expect(ed.buf:get()).to.equal({ "    hello", "bar" })
    end)
    it("o / O inherit the current line's indent when ai is on", function()
      local ed = make("    hello")
      ex.dispatch(ed, "set ai")
      feed(ed, "obelow\27")
      expect(ed.buf:get()).to.equal({ "    hello", "    below" })
      feed(ed, "Oabove\27")                          -- opens above line 2 (the new one)
      expect(ed.buf:line(2)).to.equal("    above")
    end)
    it("<CR> carries the indent onto the continuation", function()
      local ed = make("    foo")
      ex.dispatch(ed, "set ai")
      feed(ed, "A\rbar\27")                          -- append, newline, type
      expect(ed.buf:get()).to.equal({ "    foo", "    bar" })
    end)
    it("trims an autoindent-only line on <Esc>", function()
      local ed = make("    foo")
      ex.dispatch(ed, "set ai")
      feed(ed, "o\27")                               -- open, type nothing, leave
      expect(ed.buf:get()).to.equal({ "    foo", "" })
    end)
    it("<CR> on an autoindent-only line leaves it empty (no trailing blanks)", function()
      local ed = make("    foo")
      ex.dispatch(ed, "set ai")
      feed(ed, "A\r\rbar\27")
      expect(ed.buf:get()).to.equal({ "    foo", "", "    bar" })
    end)
    it("set ai? queries and ai! toggles", function()
      local ed = make("x")
      expect((ex.dispatch(ed, "set ai?"))).to.equal("noautoindent")
      ex.dispatch(ed, "set autoindent")
      expect((ex.dispatch(ed, "set ai?"))).to.equal("autoindent")
      ex.dispatch(ed, "set ai!")
      expect((ex.dispatch(ed, "set ai?"))).to.equal("noautoindent")
    end)
  end)

  describe(":[range]normal (per-line normal-mode keys)", function()
    it("runs the keys on every line of the range", function()
      local ed = make("a\nb\nc")
      ex.dispatch(ed, "%normal A;")                  -- append ; to each line
      feed(ed, "")                                   -- drain the injected key stream
      expect(ed.buf:get()).to.equal({ "a;", "b;", "c;" })
    end)
    it("can prefix a sub-range", function()
      local ed = make("a\nb\nc")
      ex.dispatch(ed, "1,2normal I#")               -- (trailing spaces are stripped from args)
      feed(ed, "")
      expect(ed.buf:get()).to.equal({ "#a", "#b", "c" })
    end)
    it("replays a macro on each line (the multi-cursor use)", function()
      local ed = make("aX\nbY\ncZ")
      ed.regs.a = { text = "x", linewise = false }   -- macro: delete the first char
      ex.dispatch(ed, "%normal @a")
      feed(ed, "")
      expect(ed.buf:get()).to.equal({ "X", "Y", "Z" })
    end)
    it("without a range still injects once at the cursor", function()
      local ed = make("hello")
      ex.dispatch(ed, "normal x")
      feed(ed, "")
      expect(ed.buf:line(1)).to.equal("ello")
    end)
  end)

  describe("edit + registers + put", function()
    it("x deletes the char under the cursor", function()
      local ed = make("abc")
      feed(ed, "x")
      expect(ed.buf:line(1)).to.equal("bc")
      expect(ed.regs['"'].text).to.equal("a")
    end)
    it("yy then p duplicates a line below", function()
      local ed = make("a\nb")
      feed(ed, "yyp")
      expect(ed.buf:get()).to.equal({ "a", "a", "b" })
      expect(ed.cy).to.equal(2)
    end)
    it("uses a named register", function()
      local ed = make("keep\ntoss")
      feed(ed, '"ayy')
      expect(ed.regs['a'].text).to.equal("keep\n")
      feed(ed, 'j"ap')                            -- put reg a below line 2
      expect(ed.buf:get()).to.equal({ "keep", "toss", "keep" })
    end)
    it("p of a multi-line charwise register splits the line (no \\n crash)", function()
      local ed = make("abc\ndef\n\nxyz")
      feed(ed, "ld}")                             -- reg = charwise "bc\ndef"
      expect(ed.regs['"'].linewise).to.be(false)
      expect(ed.regs['"'].text).to.equal("bc\ndef")
      feed(ed, "p")                               -- splits: a|bc / def, restores original
      expect(ed.buf:get()).to.equal({ "abc", "def", "", "xyz" })
      expect(ed.cy).to.equal(2)
      expect(ed.cx).to.equal(3)                   -- last char of pasted text
    end)
    it("P of a multi-line charwise register inserts before the cursor", function()
      local ed = make("abc\ndef\n\nxyz")
      feed(ed, "ld}P")                            -- put charwise "bc\ndef" before 'a'
      expect(ed.buf:get()).to.equal({ "bc", "defa", "", "xyz" })
      expect(ed.cy).to.equal(2)
      expect(ed.cx).to.equal(3)
    end)
  end)

  describe("insert mode", function()
    it("i inserts before the cursor", function()
      local ed = make("bc")
      feed(ed, "iA" .. ESC)
      expect(ed.buf:line(1)).to.equal("Abc")
      expect(ed.mode).to.equal("normal")
    end)
    it("a appends after the cursor", function()
      local ed = make("ac")
      feed(ed, "ab" .. ESC)
      expect(ed.buf:line(1)).to.equal("abc")
    end)
    it("o opens a line below and inserts", function()
      local ed = make("a\nc")
      feed(ed, "ob" .. ESC)
      expect(ed.buf:get()).to.equal({ "a", "b", "c" })
    end)
    it("<CR> in insert mode splits the line", function()
      local ed = make("ab")
      feed(ed, "i" .. "\r" .. ESC)
      expect(ed.buf:get()).to.equal({ "", "ab" })
    end)
    it("Ctrl-W erases the word before the cursor", function()
      local ed = make("")
      feed(ed, "ifoo bar\23" .. ESC)          -- type 'foo bar', Ctrl-W
      expect(ed.buf:line(1)).to.equal("foo ")
      feed(ed, "A baz qux\23" .. ESC)          -- again at end of line
      expect(ed.buf:line(1)).to.equal("foo  baz ")
    end)
    it("Ctrl-U erases from the cursor to the start of the line", function()
      local ed = make("")
      feed(ed, "ihello world\21" .. ESC)       -- type then Ctrl-U
      expect(ed.buf:line(1)).to.equal("")
    end)
    it("Ctrl-A / Ctrl-E jump to the line ends in insert mode", function()
      local ed = make("")
      feed(ed, "imiddle\1START")               -- Ctrl-A to bol, type
      feed(ed, "\5END" .. ESC)                  -- Ctrl-E to eol, type
      expect(ed.buf:line(1)).to.equal("STARTmiddleEND")
    end)
    it("cc changes a whole line", function()
      local ed = make("old\nkeep")
      feed(ed, "ccnew" .. ESC)
      expect(ed.buf:get()).to.equal({ "new", "keep" })
    end)
    it("records the last change for a future '.'", function()
      local ed = make("x")
      feed(ed, "iZ" .. ESC)
      expect(ed.last_change).to.exist()
    end)
  end)

  describe("r (replace char)", function()
    local CR = "\13"                          -- Enter in raw mode is carriage-return
    it("replaces the char under the cursor", function()
      local ed = make("hello")
      feed(ed, "rx")
      expect(ed.buf:line(1)).to.equal("xello")
    end)
    it("replaces count chars with a count", function()
      local ed = make("hello")
      feed(ed, "3rx")
      expect(ed.buf:line(1)).to.equal("xxxlo")
    end)
    it("errors (no-op) when fewer than count chars remain", function()
      local ed = make("hi")
      feed(ed, "5rx")
      expect(ed.buf:line(1)).to.equal("hi")
    end)
    -- The reported bug: r<CR> embedded a raw \r that broke rendering. It must
    -- split the line instead (POSIX), and no raw carriage-return may survive.
    it("r<CR> splits the line at the cursor", function()
      local ed = make("hello")
      feed(ed, "llr" .. CR)                    -- cursor on the first 'l'
      expect(ed.buf:get()).to.equal({ "he", "lo" })
      expect(ed.cy).to.equal(2)
      expect(ed.cx).to.equal(1)
      expect(ed.buf:line(1):find("\r")).to_not.exist()
      expect(ed.buf:line(2):find("\r")).to_not.exist()
    end)
    it("count r<CR> discards count chars, count-1 empty lines precede", function()
      local ed = make("hello")
      feed(ed, "ll2r" .. CR)
      expect(ed.buf:get()).to.equal({ "he", "", "o" })
      expect(ed.cy).to.equal(3)
    end)
    it("r<CR> at end of line leaves a trailing empty line", function()
      local ed = make("ab")
      feed(ed, "$r" .. CR)                      -- cursor on 'b' (last char)
      expect(ed.buf:get()).to.equal({ "a", "" })
    end)
    it("r<ESC> cancels with no change", function()
      local ed = make("hello")
      feed(ed, "lr" .. ESC)
      expect(ed.buf:line(1)).to.equal("hello")
    end)
    it("undoes a r<CR> split in one step", function()
      local ed = make("hello")
      feed(ed, "llr" .. CR)
      feed(ed, "u")
      expect(ed.buf:get()).to.equal({ "hello" })
    end)
  end)

  describe("'.' repeat", function()
    it("repeats the last change (delete)", function()
      local ed = make("abcde")
      feed(ed, "x")                       -- delete 'a' -> "bcde"
      feed(ed, ".")                       -- repeat -> "cde"
      expect(ed.buf:line(1)).to.equal("cde")
    end)
    it("repeats an insertion", function()
      local ed = make("Z")
      feed(ed, "ix" .. ESC)               -- "xZ", cursor on 'x'
      feed(ed, ".")                       -- insert 'x' again before cursor
      expect(ed.buf:line(1)).to.equal("xxZ")
    end)
  end)

  describe("maps", function()
    it("expands a leader map to its RHS", function()
      local ed = make("a\nb\nc")
      ex.dispatch(ed, "map \\d dd")            -- \d -> delete line
      feed(ed, "\\d")
      expect(ed.buf:get()).to.equal({ "b", "c" })
    end)
    it("is non-recursive (RHS keys are not re-mapped)", function()
      local ed = make("abc\ndef")
      ex.dispatch(ed, "map d x")                -- d -> x (delete char)
      ex.dispatch(ed, "map x dd")              -- x -> dd (should NOT fire from d's RHS)
      feed(ed, "d")
      expect(ed.buf:line(1)).to.equal("bc")    -- one char deleted, not the line
      expect(ed.buf:nlines()).to.equal(2)
    end)
    it("parses <...> notation and unmaps", function()
      local ed = make("hello")
      ex.dispatch(ed, "map <Space>x x")         -- <Space>x -> delete char (proves <Space> parse)
      feed(ed, " x")
      expect(ed.buf:line(1)).to.equal("ello")
      ex.dispatch(ed, "unmap <Space>x")
      expect(ed.maps[" x"]).to_not.exist()      -- map removed
    end)
    it("a map RHS can drive an ex command", function()
      local ed = make("x\ny\nz")
      ex.dispatch(ed, "map \\l :2d<CR>")        -- \l -> :2d
      feed(ed, "\\l")
      expect(ed.buf:get()).to.equal({ "x", "z" })
    end)
  end)

  describe("undo / redo", function()
    it("u undoes the last change; Ctrl-R redoes it", function()
      local ed = make("abc")
      feed(ed, "x"); expect(ed.buf:line(1)).to.equal("bc")
      feed(ed, "u"); expect(ed.buf:line(1)).to.equal("abc")
      feed(ed, "\18"); expect(ed.buf:line(1)).to.equal("bc")  -- Ctrl-R
    end)
    it("undoes a whole insert session as one change", function()
      local ed = make("x")
      feed(ed, "iAB" .. ESC); expect(ed.buf:line(1)).to.equal("ABx")
      feed(ed, "u"); expect(ed.buf:line(1)).to.equal("x")
    end)
    it("undoes commands one at a time", function()
      local ed = make("abc")
      feed(ed, "xx"); expect(ed.buf:line(1)).to.equal("c")
      feed(ed, "u"); expect(ed.buf:line(1)).to.equal("bc")
      feed(ed, "u"); expect(ed.buf:line(1)).to.equal("abc")
    end)
    it("undoes a dd", function()
      local ed = make("a\nb\nc")
      feed(ed, "dd"); expect(ed.buf:get()).to.equal({ "b", "c" })
      feed(ed, "u"); expect(ed.buf:get()).to.equal({ "a", "b", "c" })
    end)
    it("a status message survives until the next command's key", function()
      local ed = make("a")
      feed(ed, "u")                              -- nothing to undo -> sets a message
      expect(ed.message).to.equal("Already at oldest change")
      feed(ed, "j")                              -- next command clears it
      expect(ed.message).to_not.exist()
    end)
  end)

  describe("macros", function()
    it("records into a register and replays with @", function()
      local ed = make("a\nb\nc\nd")
      feed(ed, "qaddq")                    -- record 'dd' into reg a (deletes 'a')
      expect(ed.regs['a'].text).to.equal("dd")
      expect(ed.buf:get()).to.equal({ "b", "c", "d" })
      feed(ed, "@a")                       -- replay -> deletes 'b'
      expect(ed.buf:get()).to.equal({ "c", "d" })
    end)
    it("honors a count on @", function()
      local ed = make("1\n2\n3\n4\n5")
      feed(ed, "qxddq")                    -- reg x = 'dd', deletes '1'
      feed(ed, "2@x")                      -- delete two more lines
      expect(ed.buf:get()).to.equal({ "4", "5" })
    end)
    it("@@ repeats the last macro", function()
      local ed = make("1\n2\n3\n4")
      feed(ed, "qaddq")                    -- {2,3,4}
      feed(ed, "@a")                       -- {3,4}
      feed(ed, "@@")                       -- {4}
      expect(ed.buf:get()).to.equal({ "4" })
    end)
    it("records a multi-key edit macro", function()
      local ed = make("x\nx\nx")
      feed(ed, "qbA!" .. ESC .. "jq")      -- append '!' to a line, go down; reg b
      expect(ed.regs['b'].text).to.equal("A!" .. ESC .. "j")
      feed(ed, "@b@b")                      -- apply to the next two lines
      expect(ed.buf:get()).to.equal({ "x!", "x!", "x!" })
    end)
  end)

  describe(":normal send-keys", function()
    it("runs normal-mode keys given at the ':' prompt", function()
      local ed = make("foo bar")
      feed(ed, ":normal dw\r")            -- dw over the send-keys hatch
      expect(ed.buf:line(1)).to.equal("bar")
    end)
    it("leaves last_change set so '.' can repeat send-keys", function()
      local ed = make("one two three")
      feed(ed, ":normal dw\r")            -- "two three"
      feed(ed, ".")                       -- dw again -> "three"
      expect(ed.buf:line(1)).to.equal("three")
    end)
  end)

  describe("the ':' prompt accepts UTF-8", function()
    it("multibyte bytes reach the command line", function()
      local ed = make("x")
      feed(ed, ":echo héllo\r")           -- é is two bytes; both must pass
      expect(ed.message).to.equal("héllo")
    end)
    it("backspace erases a whole multibyte char, not one byte", function()
      local ed = make("x")
      feed(ed, ":echo aé\127b\r")         -- one BS must kill both bytes of é
      expect(ed.message).to.equal("ab")   -- byte-wise BS would leave a stray 0xC3
    end)
  end)

  describe("scrolling (Ctrl-F/B/D/U/E/Y)", function()
    -- A tall nowrap window: 100 short lines, rows=12 -> textrows=11, half=5,
    -- page=9 (11-2 overlap). One buffer line == one screen row, so top/cursor
    -- math is exact.
    local function tall()
      local t = {}
      for i = 1, 100 do t[i] = "line " .. i end
      local ed = make(table.concat(t, "\n"))
      ed.opts = { wrap = false, tabstop = 8 }
      ed.rows = 12
      return ed
    end
    local CF, CB, CD, CU, CE, CY = "\6", "\2", "\4", "\21", "\5", "\25"

    it("Ctrl-F/Ctrl-B page down and up (cursor keeps its screen row)", function()
      local ed = tall()
      feed(ed, CF); expect(ed.top).to.equal(10); expect(ed.cy).to.equal(10)
      feed(ed, CF); expect(ed.top).to.equal(19); expect(ed.cy).to.equal(19)
      feed(ed, CB); expect(ed.top).to.equal(10); expect(ed.cy).to.equal(10)
    end)

    it("Ctrl-D/Ctrl-U scroll half a page", function()
      local ed = tall()
      feed(ed, CD); expect(ed.top).to.equal(6);  expect(ed.cy).to.equal(6)
      feed(ed, CD); expect(ed.top).to.equal(11); expect(ed.cy).to.equal(11)
      feed(ed, CU); expect(ed.top).to.equal(6);  expect(ed.cy).to.equal(6)
    end)

    it("a count sets the scroll size for Ctrl-D", function()
      local ed = tall()
      feed(ed, "3" .. CD); expect(ed.top).to.equal(4); expect(ed.cy).to.equal(4)
    end)

    it("Ctrl-E reveals a lower line, keeping the cursor put until it scrolls off", function()
      local ed = tall()
      feed(ed, "4j"); expect(ed.cy).to.equal(5)     -- cursor mid-screen (row offset 4)
      feed(ed, CE); expect(ed.top).to.equal(2); expect(ed.cy).to.equal(5)  -- line kept
      feed(ed, CE .. CE .. CE)                       -- top climbs to the cursor's line
      expect(ed.top).to.equal(5); expect(ed.cy).to.equal(5)
      feed(ed, CE); expect(ed.top).to.equal(6); expect(ed.cy).to.equal(6)  -- now dragged
    end)

    it("Ctrl-Y reveals a higher line, keeping the cursor put mid-screen", function()
      local ed = tall()
      feed(ed, CD); expect(ed.top).to.equal(6); expect(ed.cy).to.equal(6) -- cursor on top row
      feed(ed, CY); expect(ed.top).to.equal(5); expect(ed.cy).to.equal(6) -- line kept, window up
    end)

    it("Ctrl-Y drags the cursor up when it sits on the bottom edge", function()
      local ed = tall()
      feed(ed, CD);       expect(ed.top).to.equal(6)  -- top=6
      feed(ed, "10j");    expect(ed.cy).to.equal(16)  -- cursor on the bottom row (offset 10)
      feed(ed, CY); expect(ed.top).to.equal(5); expect(ed.cy).to.equal(15) -- dragged up one
    end)

    it("does not scroll past the top of the buffer", function()
      local ed = tall()
      feed(ed, CB); expect(ed.top).to.equal(1); expect(ed.cy).to.equal(1)
      feed(ed, CY); expect(ed.top).to.equal(1)
    end)

    it("advances the sub-row when the top line wraps (wrap mode)", function()
      local long = string.rep("x", 200)            -- 200 cols / W=80 -> 3 sub-rows
      local ed = make(long .. "\na\nb\nc")
      ed.opts = { wrap = true, tabstop = 8 }
      ed.rows = 12; ed.cols = 80; ed.top = 1; ed.topsub = 0
      feed(ed, "\5")                                -- Ctrl-E: reveal one screen row
      expect(ed.top).to.equal(1); expect(ed.topsub).to.equal(1)
    end)
  end)

  describe("derived edit commands D C Y s S X J ~", function()
    it("D deletes from the cursor to end-of-line", function()
      local ed = make("hello world")
      feed(ed, "6lD")
      expect(ed.buf:line(1)).to.equal("hello ")
      expect(ed.regs['"'].text).to.equal("world")
    end)
    it("2D deletes to EOL plus the whole next line", function()
      local ed = make("abcdef\nghijkl\nmnop")
      feed(ed, "3l2D")
      expect(ed.buf:get()).to.equal({ "abc", "mnop" })
    end)
    it("C changes to end-of-line and enters insert", function()
      local ed = make("hello world")
      feed(ed, "6lCthere" .. ESC)
      expect(ed.buf:line(1)).to.equal("hello there")
      expect(ed.mode).to.equal("normal")
    end)
    it("Y yanks the current line linewise; 2Y yanks two", function()
      local ed = make("one\ntwo\nthree")
      feed(ed, "Y")
      expect(ed.regs['"'].text).to.equal("one\n")
      expect(ed.regs['"'].linewise).to.be(true)
      feed(ed, "2Y")
      expect(ed.regs['"'].text).to.equal("one\ntwo\n")
    end)
    it("s substitutes count chars and enters insert", function()
      local ed = make("hello")
      feed(ed, "2sXY" .. ESC)
      expect(ed.buf:line(1)).to.equal("XYllo")
    end)
    it("s on an empty line still enters insert", function()
      local ed = make("")
      feed(ed, "shi" .. ESC)
      expect(ed.buf:line(1)).to.equal("hi")
    end)
    it("S changes the whole line", function()
      local ed = make("hello\nworld")
      feed(ed, "Snew" .. ESC)
      expect(ed.buf:get()).to.equal({ "new", "world" })
    end)
    it("X deletes the char before the cursor", function()
      local ed = make("hello")
      feed(ed, "3lX")     -- cursor on 'l' (col 4); delete the char before it
      expect(ed.buf:line(1)).to.equal("helo")
      expect(ed.cx).to.equal(3)
    end)
    it("X is a no-op at column 1", function()
      local ed = make("hello")
      feed(ed, "X")
      expect(ed.buf:line(1)).to.equal("hello")
    end)
    it("J joins lines with a separating space", function()
      local ed = make("foo\nbar")
      feed(ed, "J")
      expect(ed.buf:line(1)).to.equal("foo bar")
      expect(ed.cx).to.equal(4)   -- on the join space
    end)
    it("J strips leading blanks and skips the space before ')'", function()
      local ed = make("foo\n   bar")
      feed(ed, "J")
      expect(ed.buf:line(1)).to.equal("foo bar")
      local ed2 = make("foo\n)bar")
      feed(ed2, "J")
      expect(ed2.buf:line(1)).to.equal("foo)bar")
    end)
    it("3J joins three lines", function()
      local ed = make("a\nb\nc\nd")
      feed(ed, "3J")
      expect(ed.buf:get()).to.equal({ "a b c", "d" })
    end)
    it("~ toggles case and advances", function()
      local ed = make("aB.c")
      feed(ed, "~")
      expect(ed.buf:line(1)).to.equal("AB.c")
      expect(ed.cx).to.equal(2)
      feed(ed, "~")
      expect(ed.buf:line(1)).to.equal("Ab.c")
    end)
    it("3~ toggles a run", function()
      local ed = make("abcd")
      feed(ed, "3~")
      expect(ed.buf:line(1)).to.equal("ABCd")
      expect(ed.cx).to.equal(4)
    end)
    it("D and . repeat", function()
      local ed = make("abcXdef\nabcYdef")
      feed(ed, "3lD")
      expect(ed.buf:line(1)).to.equal("abc")
      feed(ed, "j0.")
      expect(ed.buf:line(2)).to.equal("")
    end)
  end)

  describe("paragraph motions { }", function()
    -- 1:p1a 2:p1b 3:"" 4:p2a 5:p2b 6:"" 7:p3
    local function paras() return make("p1a\np1b\n\np2a\np2b\n\np3") end
    it("} moves forward to the next empty line, then EOF", function()
      local ed = paras()
      feed(ed, "}"); expect(ed.cy).to.equal(3)
      feed(ed, "}"); expect(ed.cy).to.equal(6)
      feed(ed, "}"); expect(ed.cy).to.equal(7)   -- last line
    end)
    it("{ moves backward to the previous empty line, then BOF", function()
      local ed = paras()
      feed(ed, "G");  expect(ed.cy).to.equal(7)
      feed(ed, "{");  expect(ed.cy).to.equal(6)
      feed(ed, "{");  expect(ed.cy).to.equal(3)
      feed(ed, "{");  expect(ed.cy).to.equal(1)
    end)
    it("honors a count", function()
      local ed = paras()
      feed(ed, "2}"); expect(ed.cy).to.equal(6)
    end)
    it("lands on column 1 of the boundary", function()
      local ed = paras()
      feed(ed, "ll}"); expect(ed.cx).to.equal(1)
    end)
    it("d} deletes charwise up to the boundary", function()
      local ed = make("abc\ndef\n\nxyz")
      feed(ed, "ld}")   -- from (1,2) exclusive to the blank line
      expect(ed.buf:get()).to.equal({ "a", "", "xyz" })
    end)
  end)

  describe("section motions [[ ]]", function()
    -- 1:{ 2:foo 3:bar 4:{ 5:baz
    local function secs() return make("{\nfoo\nbar\n{\nbaz") end
    it("]] moves forward to the next section boundary, then EOF", function()
      local ed = secs()
      feed(ed, "]]"); expect(ed.cy).to.equal(4)
      feed(ed, "]]"); expect(ed.cy).to.equal(5)
    end)
    it("[[ moves backward to the previous section boundary", function()
      local ed = secs()
      feed(ed, "G");   expect(ed.cy).to.equal(5)
      feed(ed, "[[");  expect(ed.cy).to.equal(4)
      feed(ed, "[[");  expect(ed.cy).to.equal(1)
    end)
    it("]] ignores empty lines (only sections)", function()
      local ed = make("a\n\nb\n{\nc")   -- blank line 2 is NOT a section boundary
      feed(ed, "]]"); expect(ed.cy).to.equal(4)
    end)
    it("a lone ] is a no-op (waits for the pair, discards the key)", function()
      local ed = secs()
      feed(ed, "]x"); expect(ed.cy).to.equal(1)  -- ']' then 'x' -> no move
    end)
    it("d]] deletes to the next section boundary", function()
      local ed = make("foo\nbar\n{\nbaz")
      feed(ed, "ld]]")   -- from (1,2) to the '{' line, exclusive
      expect(ed.buf:get()).to.equal({ "f", "{", "baz" })
    end)
  end)

  describe("bigword motions W B E", function()
    it("W skips over punctuation (whitespace-delimited)", function()
      local ed = make("foo.bar baz")
      feed(ed, "w"); expect(ed.cx).to.equal(4)   -- w stops at '.'
      local ed2 = make("foo.bar baz")
      feed(ed2, "W"); expect(ed2.cx).to.equal(9) -- W jumps to 'baz'
    end)
    it("B moves back over a whole bigword", function()
      local ed = make("foo.bar baz")
      feed(ed, "$");  expect(ed.cx).to.equal(11)
      feed(ed, "B");  expect(ed.cx).to.equal(9)  -- start of 'baz'
      feed(ed, "B");  expect(ed.cx).to.equal(1)  -- start of 'foo.bar'
    end)
    it("E moves to the end of a bigword", function()
      local ed = make("foo.bar baz")
      feed(ed, "E");  expect(ed.cx).to.equal(7)  -- end of 'foo.bar'
      feed(ed, "E");  expect(ed.cx).to.equal(11) -- end of 'baz'
    end)
    it("dW deletes through punctuation to the next bigword", function()
      local ed = make("foo.bar baz")
      feed(ed, "dW")
      expect(ed.buf:line(1)).to.equal("baz")
    end)
    it("w/b/e still stop at punctuation boundaries", function()
      local ed = make("a.b c")
      feed(ed, "w"); expect(ed.cx).to.equal(2)   -- '.'
      feed(ed, "w"); expect(ed.cx).to.equal(3)   -- 'b'
    end)
  end)

  describe("match bracket %", function()
    it("jumps from an open bracket to its match", function()
      local ed = make("a(bcd)e")
      feed(ed, "f(%")
      expect(ed.cx).to.equal(6)   -- the ')'
    end)
    it("jumps from a close bracket back to its match", function()
      local ed = make("a(bcd)e")
      feed(ed, "f)%")
      expect(ed.cx).to.equal(2)   -- back to '('
    end)
    it("searches forward on the line when not on a bracket", function()
      local ed = make("foo (bar) baz")
      feed(ed, "%")               -- cursor at col 1, first bracket is '(' at 5
      expect(ed.cx).to.equal(9)   -- its ')'
    end)
    it("honors nesting of the same type", function()
      local ed = make("(a(b)c)")
      feed(ed, "%")
      expect(ed.cx).to.equal(7)   -- outer ')'
    end)
    it("matches across lines", function()
      local ed = make("foo(\n  bar\n)baz")
      feed(ed, "f(%")
      expect(ed.cy).to.equal(3); expect(ed.cx).to.equal(1)
    end)
    it("is a no-op when the line has no bracket", function()
      local ed = make("plain text")
      feed(ed, "%")
      expect(ed.cy).to.equal(1); expect(ed.cx).to.equal(1)
    end)
    it("d% deletes inclusively across the pair", function()
      local ed = make("x(abc)y")
      feed(ed, "f(d%")
      expect(ed.buf:line(1)).to.equal("xy")
    end)
  end)

  describe("sentence motions ( )", function()
    it(") moves to the next sentence (2 spaces, then EOL)", function()
      -- "One.  Two.  Three" : starts at cols 1, 7, 13
      local ed = make("One.  Two.  Three")
      feed(ed, ")");  expect(ed.cx).to.equal(7)
      feed(ed, ")");  expect(ed.cx).to.equal(13)
    end)
    it("( moves back to the sentence start", function()
      local ed = make("One.  Two.  Three")
      feed(ed, "$");  expect(ed.cx).to.equal(17)
      feed(ed, "(");  expect(ed.cx).to.equal(13)
      feed(ed, "(");  expect(ed.cx).to.equal(7)
      feed(ed, "(");  expect(ed.cx).to.equal(1)
    end)
    it("does NOT break on a single space (POSIX two-space rule)", function()
      local ed = make("a. b. c")   -- single spaces -> one sentence on the line
      feed(ed, ")")
      expect(ed.cy).to.equal(1); expect(ed.cx).to.equal(7)  -- stops at EOF (last char)
    end)
    it("treats a terminator at end-of-line as a break", function()
      local ed = make("Done.\nNext one")
      feed(ed, ")")
      expect(ed.cy).to.equal(2); expect(ed.cx).to.equal(1)
    end)
    it("skips closing quotes/brackets before the break", function()
      local ed = make('He said "hi."  Bye')   -- .")  two spaces -> start at "Bye"
      feed(ed, ")")
      expect(ed.cx).to.equal(16)   -- 'B' of Bye
    end)
    it("treats a blank line as a sentence boundary", function()
      local ed = make("first\n\nsecond")
      feed(ed, ")");  expect(ed.cy).to.equal(2)   -- the empty line
      feed(ed, ")");  expect(ed.cy).to.equal(3); expect(ed.cx).to.equal(1)
    end)
    it("honors a count", function()
      local ed = make("One.  Two.  Three")
      feed(ed, "2)"); expect(ed.cx).to.equal(13)
    end)
    it("d) deletes the sentence charwise-exclusive", function()
      local ed = make("One.  Two.  Three")
      feed(ed, "d)")
      expect(ed.buf:line(1)).to.equal("Two.  Three")
    end)
  end)

  describe("shift operators < >", function()
    it(">> indents by shiftwidth, tab-optimized by default", function()
      local ed = make("foo\nbar")
      feed(ed, ">>")                       -- default sw=8, ts=8, noexpandtab
      expect(ed.buf:line(1)).to.equal("\tfoo")
      expect(ed.cx).to.equal(2)            -- first non-blank
    end)
    it("<< removes a level of indent", function()
      local ed = make("\tfoo")
      feed(ed, "<<")
      expect(ed.buf:line(1)).to.equal("foo")
    end)
    it("respects :set shiftwidth and expandtab", function()
      local ed = make("foo")
      feed(ed, ":set sw=2 expandtab\r")
      feed(ed, ">>")
      expect(ed.buf:line(1)).to.equal("  foo")
      feed(ed, ">>")
      expect(ed.buf:line(1)).to.equal("    foo")
    end)
    it("2>> shifts a count of lines", function()
      local ed = make("a\nb\nc")
      feed(ed, ":set sw=2 et\r")
      feed(ed, "2>>")
      expect(ed.buf:get()).to.equal({ "  a", "  b", "c" })
    end)
    it(">j shifts the lines a motion spans", function()
      local ed = make("a\nb\nc")
      feed(ed, ":set sw=2 et\r")
      feed(ed, ">j")
      expect(ed.buf:get()).to.equal({ "  a", "  b", "c" })
    end)
    it("leaves an empty line unchanged on right shift", function()
      local ed = make("foo\n\nbar")
      feed(ed, ":set sw=2 et\r")
      feed(ed, "2>j")   -- shift 3 lines (current + 2 down)
      expect(ed.buf:get()).to.equal({ "  foo", "", "  bar" })
    end)
    it("a whole multi-line shift undoes as one change", function()
      local ed = make("a\nb\nc")
      feed(ed, ":set sw=2 et\r")
      feed(ed, "2>>")
      feed(ed, "u")
      expect(ed.buf:get()).to.equal({ "a", "b", "c" })
    end)
  end)

  describe("R (replace/overwrite mode)", function()
    it("overwrites characters in place", function()
      local ed = make("hello")
      feed(ed, "RXYZ" .. ESC)
      expect(ed.buf:line(1)).to.equal("XYZlo")
    end)
    it("extends the line when typing past end-of-line", function()
      local ed = make("ab")
      feed(ed, "RXYZW" .. ESC)
      expect(ed.buf:line(1)).to.equal("XYZW")
    end)
    it("backspace moves left without restoring", function()
      local ed = make("hello")
      feed(ed, "RXY\127Z" .. ESC)   -- type XY, backspace over Y, type Z
      expect(ed.buf:line(1)).to.equal("XZllo")
    end)
    it("leaves the cursor stepped back on <Esc>, like insert", function()
      local ed = make("hello")
      feed(ed, "RAB" .. ESC)
      expect(ed.buf:line(1)).to.equal("ABllo")
      expect(ed.cx).to.equal(2)
      expect(ed.mode).to.equal("normal")
    end)
    it("is repeatable with .", function()
      local ed = make("aaaa\nbbbb")
      feed(ed, "RXX" .. ESC)
      expect(ed.buf:line(1)).to.equal("XXaa")
      feed(ed, "j0.")
      expect(ed.buf:line(2)).to.equal("XXbb")
    end)
  end)

  describe("screen-position motions H M L", function()
    local function tall()
      local lines = {}
      for i = 1, 30 do lines[i] = "line" .. i end
      local ed = make(table.concat(lines, "\n"))
      ed.rows = 11; ed.top = 5   -- textrows = 10, showing lines 5..14
      return ed
    end
    it("H goes to the top of the screen (+count)", function()
      local ed = tall()
      feed(ed, "H");  expect(ed.cy).to.equal(5)
      feed(ed, "3H"); expect(ed.cy).to.equal(7)
    end)
    it("L goes to the bottom of the screen (-count)", function()
      local ed = tall()
      feed(ed, "L");  expect(ed.cy).to.equal(14)
      feed(ed, "2L"); expect(ed.cy).to.equal(13)
    end)
    it("M goes to the middle of the screen", function()
      local ed = tall()
      feed(ed, "M"); expect(ed.cy).to.equal(9)   -- (5 + 14) / 2
    end)
    it("dH deletes linewise up to the top of the screen", function()
      local ed = tall()
      feed(ed, "7GdH")   -- from line 7 up to top (line 5): delete 5,6,7
      expect(ed.buf:line(5)).to.equal("line8")
    end)
    it("L/M stay on-screen when a top line wraps", function()
      -- line 1 is 25 cols wide; at W=10 it spans 3 screen rows.
      local ed = make(string.rep("x", 25) .. "\na\nb\nc\nd")
      ed.opts = { wrap = true, tabstop = 8 }
      ed.rows = 5; ed.cols = 10; ed.top = 1; ed.topsub = 0
      -- 4 text rows = line1's 3 rows + line2 -> only lines 1 and 2 are visible.
      feed(ed, "H"); expect(ed.cy).to.equal(1)
      feed(ed, "L"); expect(ed.cy).to.equal(2)   -- not line 3 (the old buggy result)
      feed(ed, "M"); expect(ed.cy).to.equal(1)
    end)
  end)

  describe("z reposition and Ctrl-G", function()
    local function tall()
      local lines = {}
      for i = 1, 30 do lines[i] = "L" .. i end
      local ed = make(table.concat(lines, "\n"))
      ed.rows = 11   -- textrows = 10
      return ed
    end
    it("z<CR> puts the current line at the top", function()
      local ed = tall()
      feed(ed, "15G"); feed(ed, "z\r")
      expect(ed.top).to.equal(15); expect(ed.cy).to.equal(15)
    end)
    it("z. centers the current line", function()
      local ed = tall()
      feed(ed, "15Gz.")
      expect(ed.top).to.equal(10)  -- 15 - floor(10/2)
    end)
    it("z- puts the current line at the bottom", function()
      local ed = tall()
      feed(ed, "15Gz-")
      expect(ed.top).to.equal(6)   -- 15 - (10 - 1)
    end)
    it("[count]z<CR> repositions around a given line", function()
      local ed = tall()
      feed(ed, "20z\r")
      expect(ed.top).to.equal(20); expect(ed.cy).to.equal(20)
    end)
    it("zt puts the current line at the top, keeping the column", function()
      local ed = tall()
      feed(ed, "15Glzt")                          -- line 15, one col right, then zt
      expect(ed.top).to.equal(15); expect(ed.cy).to.equal(15)
      expect(ed.cx).to.equal(2)                   -- column kept (z<CR> -> first non-blank = 1)
    end)
    it("zz centers the current line, keeping the column", function()
      local ed = tall()
      feed(ed, "15Gllzz")
      expect(ed.top).to.equal(10)                 -- 15 - floor(10/2)
      expect(ed.cy).to.equal(15); expect(ed.cx).to.equal(3)
    end)
    it("zb puts the current line at the bottom, keeping the column", function()
      local ed = tall()
      feed(ed, "15Glzb")
      expect(ed.top).to.equal(6)                  -- 15 - (10 - 1)
      expect(ed.cy).to.equal(15); expect(ed.cx).to.equal(2)
    end)
    it("[count]zt keeps the column across the line change", function()
      local ed = tall()
      feed(ed, "l20zt")                           -- col 2 on line 1, then 20zt
      expect(ed.top).to.equal(20); expect(ed.cy).to.equal(20)
      expect(ed.cx).to.equal(2)
    end)
    it("zz centers a wrapping line by SCREEN rows, not buffer lines (wrap on)", function()
      -- 9 lines each wrapping into 2 screen rows at cols=4. Centering the last
      -- line (textrows 10 -> 5 rows up) must count screen rows: buffer-line math
      -- would wrongly land at top=4, and refresh() would then pin it to the
      -- bottom (the reported wrap bug). Screen-row math lands at top=6,topsub=1.
      local ed = make(("abcdef\n"):rep(9))
      ed.opts = { wrap = true, tabstop = 8 }; ed.cols = 4; ed.rows = 11
      feed(ed, "Gzz")
      expect(ed.cy).to.equal(9)
      expect(ed.top).to.equal(6); expect(ed.topsub).to.equal(1)
      editor.refresh(ed)                          -- the driver's clamp must not undo it
      expect(ed.top).to.equal(6); expect(ed.topsub).to.equal(1)
    end)
    it("Ctrl-G reports file position on the message line", function()
      local ed = tall()
      feed(ed, "15G\7")
      expect(ed.message).to.exist()
      expect(ed.message:find("line 15 of 30", 1, true)).to.exist()
    end)
  end)

  describe("ZZ / ZQ", function()
    it("ZQ quits without writing", function()
      local ed = make("dirty")
      feed(ed, "x")                 -- make it modified
      expect(ed.buf.modified).to.be(true)
      feed(ed, "ZQ")
      expect(ed.running).to.be(false)
    end)
    it("ZZ on a modified unnamed buffer errors instead of quitting", function()
      local ed = make("hello")
      feed(ed, "x")                 -- modify it: :x must write, but there is no path
      expect(ed.buf.modified).to.be(true)
      feed(ed, "ZZ")
      expect(ed.running).to.be(true)
      expect(ed.message).to.exist()
    end)
    it("ZZ on a clean unnamed buffer quits without writing", function()
      local ed = make("hello")   -- unmodified, so :x skips the write and just quits
      feed(ed, "ZZ")
      expect(ed.running).to.be(false)
    end)
  end)

  describe("the ':' prompt shares ex.dispatch", function()
    it("runs an ex command typed at ':'", function()
      local ed = make("a\nb\nc")
      feed(ed, ":2d\r")
      expect(ed.buf:get()).to.equal({ "a", "c" })
      expect(ed.mode).to.equal("normal")
    end)
    it(":q sets running=false", function()
      local ed = make("a")
      feed(ed, ":q\r")
      expect(ed.running).to.be(false)
    end)
    it("Esc cancels the prompt without running the command", function()
      local ed = make("a\nb\nc")
      feed(ed, ":2d" .. ESC)
      expect(ed.buf:get()).to.equal({ "a", "b", "c" })
      expect(ed.mode).to.equal("normal")
      expect(ed.cmdline).to.equal("")
    end)
    it("Ctrl-C cancels the prompt without running the command", function()
      local ed = make("a\nb\nc")
      feed(ed, ":2d\3")
      expect(ed.buf:get()).to.equal({ "a", "b", "c" })
      expect(ed.mode).to.equal("normal")
      expect(ed.cmdline).to.equal("")
    end)
  end)

  describe("insert-mode completion (Ctrl-P/Ctrl-N)", function()
    -- Stub the completer: record the context core hands over, return a canned word.
    local function with_completer(ed, ret)
      local seen = {}
      ed.hooks = { complete = { "stub" } }
      ed.complete_run = function(cmd, token, left, dir)
        seen.cmd, seen.token, seen.left, seen.dir = cmd, token, left, dir
        return ret
      end
      return seen
    end
    local CP, CN = string.char(16), string.char(14)

    it("replaces the token before the cursor with the completer's word", function()
      local ed = make("")
      local seen = with_completer(ed, "foobar")
      feed(ed, "ifoo" .. CP)
      expect(ed.buf:line(1)).to.equal("foobar")
      expect(ed.cx).to.equal(7)                 -- cursor after the inserted word
      expect(seen.token).to.equal("foo")        -- the non-blank run before cursor
      expect(seen.dir).to.equal("prev")         -- Ctrl-P
    end)

    it("extracts the token as the non-blank run and preserves text after the cursor", function()
      local ed = make("fooXYZ")
      local seen = with_completer(ed, "foobar")
      feed(ed, "llli" .. CP)                     -- cursor on 'X', insert before it
      expect(seen.token).to.equal("foo")
      expect(seen.left).to.equal("foo")
      expect(ed.buf:line(1)).to.equal("foobarXYZ")
    end)

    it("Ctrl-N passes dir=next", function()
      local ed = make("")
      local seen = with_completer(ed, "x")
      feed(ed, "ia" .. CN)
      expect(seen.dir).to.equal("next")
    end)

    it("an empty completion result leaves the buffer unchanged", function()
      local ed = make("")
      with_completer(ed, "")
      feed(ed, "ifoo" .. CP)
      expect(ed.buf:line(1)).to.equal("foo")
      expect(ed.cx).to.equal(4)
    end)

    it("is a no-op with no completer registered", function()
      local ed = make("")
      feed(ed, "ifoo" .. CP .. "bar")            -- Ctrl-P ignored; typing continues
      expect(ed.buf:line(1)).to.equal("foobar")
    end)
  end)

  describe("jumplist (Ctrl-O / Ctrl-I)", function()
    local CO, CI = "\15", "\9"                    -- Ctrl-O, Ctrl-I (Tab)
    it("Ctrl-O walks back over jumps and Ctrl-I forward", function()
      local ed = make("l1\nl2\nl3\nl4\nl5")
      feed(ed, "G");  expect(ed.cy).to.equal(5)   -- jump from line 1
      feed(ed, "2G"); expect(ed.cy).to.equal(2)   -- jump from line 5
      feed(ed, CO);   expect(ed.cy).to.equal(5)   -- back to the line 2 jump's origin
      feed(ed, CO);   expect(ed.cy).to.equal(1)   -- back to the G jump's origin
      feed(ed, CO);   expect(ed.cy).to.equal(1)   -- nothing older: stays put
      feed(ed, CI);   expect(ed.cy).to.equal(5)   -- forward again
      feed(ed, CI);   expect(ed.cy).to.equal(2)   -- back to the live edge (line 2)
      feed(ed, CI);   expect(ed.cy).to.equal(2)   -- nothing newer: stays put
    end)
    it("non-jump motions do not push, and Ctrl-O/I are no-ops when empty", function()
      local ed = make("l1\nl2\nl3\nl4\nl5")
      feed(ed, "jjj"); expect(ed.cy).to.equal(4)  -- j is not jump-class
      feed(ed, CO);    expect(ed.cy).to.equal(4)  -- empty jumplist: no move
      feed(ed, CI);    expect(ed.cy).to.equal(4)
    end)
    it("dedups by line so revisiting a line doesn't bloat the list", function()
      local ed = make("l1\nl2\nl3\nl4\nl5")
      feed(ed, "G");   feed(ed, "1G")             -- jump to 5, then back to 1
      feed(ed, "G")                               -- jump to 5 again (origin line 1 dup)
      expect(#ed.jumps.list).to.equal(2)          -- {5, 1}, not {1, 5, 1}
    end)
  end)
end)

os.exit(lust.errors == 0 and 0 or 1)
